import { Chapter } from "@/types";

export const dataInsightsChapters: Chapter[] = [
  {
    id: "di-data-sufficiency",
    section: "data-insights",
    title: "Data Sufficiency Fundamentals",
    description: "Master the Data Sufficiency format: determine whether given statements provide enough information to answer a question, without actually solving it. The most common DI question type.",
    order: 1,
    topics: ["ds-number-properties", "ds-algebra", "ds-word-problems", "ds-statistics"],
    frequency: "high",
    estimatedMinutes: 45,
    practiceQuestionIds: ["dq1", "dq2", "dq3", "dq4", "dq5", "dq6", "dq7", "dq8", "dq9", "dq10", "dq11", "dq12", "dq13", "dq14", "dq15", "dq16", "dq17", "dq18", "dq19", "dq20"],
  },
  {
    id: "di-multi-source",
    section: "data-insights",
    title: "Multi-Source Reasoning",
    description: "Synthesize information from multiple tabs — emails, reports, tables, and charts — to answer questions. Requires careful cross-referencing.",
    order: 2,
    topics: ["msr"],
    frequency: "high",
    estimatedMinutes: 40,
    practiceQuestionIds: ["dq21", "dq22", "dq23", "dq24", "dq25", "dq26", "dq27", "dq28", "dq29", "dq30", "dq31", "dq32", "dq33", "dq34", "dq35"],
  },
  {
    id: "di-two-part",
    section: "data-insights",
    title: "Two-Part Analysis",
    description: "Solve problems that require finding two related values simultaneously — often involving algebra, logic, or optimization with a two-column answer format.",
    order: 3,
    topics: ["tpa"],
    frequency: "medium",
    estimatedMinutes: 35,
    practiceQuestionIds: ["dq36", "dq37", "dq38", "dq39", "dq40", "dq41", "dq42", "dq43", "dq44", "dq45"],
  },
  {
    id: "di-graphics",
    section: "data-insights",
    title: "Graphics Interpretation",
    description: "Interpret data from graphs, charts, and diagrams — including scatter plots, bar charts, line graphs, and Venn diagrams — to fill in statements or answer questions.",
    order: 4,
    topics: ["gi"],
    frequency: "medium",
    estimatedMinutes: 30,
    practiceQuestionIds: ["dq46", "dq47", "dq48", "dq49", "dq50", "dq51", "dq52", "dq53"],
  },
  {
    id: "di-table",
    section: "data-insights",
    title: "Table Analysis",
    description: "Analyze sortable data tables to determine whether statements are supported by the data. Requires careful reading and basic calculations.",
    order: 5,
    topics: ["ta"],
    frequency: "medium",
    estimatedMinutes: 30,
    practiceQuestionIds: ["dq54", "dq55", "dq56", "dq57", "dq58", "dq59", "dq60"],
  },
];
