import { Question } from "@/types";

export const greQuantQuestions: Question[] = [
  {
    id: "gre-q-001",
    section: "quant",
    type: "quantitative-comparison",
    themes: ["integers"],
    difficulty: "easy",
    text: "Column A: The number of prime numbers between 20 and 30\nColumn B: 2\n\nCompare the two quantities.",
    choices: [
      "Column A is greater",
      "Column B is greater",
      "The two quantities are equal",
      "The relationship cannot be determined from the information given",
    ],
    correctAnswer: 2,
    explanation: "The prime numbers between 20 and 30 are 23 and 29 — that's exactly 2 primes. Column A = 2 and Column B = 2, so they are equal.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-q-002",
    section: "quant",
    type: "problem-solving",
    themes: ["linear-equations"],
    difficulty: "medium",
    text: "If 3x + 7 = 22, what is the value of 6x + 3?",
    choices: ["27", "30", "33", "36", "39"],
    correctAnswer: 2,
    explanation: "First solve for x: 3x + 7 = 22, so 3x = 15 and x = 5. Then 6x + 3 = 6(5) + 3 = 30 + 3 = 33. Alternatively, notice that 6x + 3 = 2(3x) + 3 = 2(15) + 3 = 33.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-q-003",
    section: "quant",
    type: "quantitative-comparison",
    themes: ["triangles"],
    difficulty: "medium",
    text: "In triangle PQR, PQ = 5, QR = 7, and PR = 9.\n\nColumn A: The measure of angle Q\nColumn B: 90 degrees",
    choices: [
      "Column A is greater",
      "Column B is greater",
      "The two quantities are equal",
      "The relationship cannot be determined from the information given",
    ],
    correctAnswer: 0,
    explanation: "In a triangle, the largest angle is opposite the longest side. The longest side is PR = 9, so angle Q (opposite PR) is the largest angle. To check if it's obtuse: by the converse of the Pythagorean theorem, if PR\u00b2 > PQ\u00b2 + QR\u00b2, angle Q is obtuse. 9\u00b2 = 81 > 5\u00b2 + 7\u00b2 = 25 + 49 = 74. Since 81 > 74, angle Q > 90\u00b0, so Column A is greater.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-q-004",
    section: "quant",
    type: "problem-solving",
    themes: ["probability"],
    difficulty: "medium",
    text: "A bag contains 5 red balls and 3 blue balls. If two balls are drawn at random without replacement, what is the probability that both balls are red?",
    choices: ["5/14", "25/64", "5/8", "10/28", "15/56"],
    correctAnswer: 0,
    explanation: "P(1st red) = 5/8. After drawing a red ball, P(2nd red) = 4/7. P(both red) = (5/8) \u00d7 (4/7) = 20/56 = 5/14.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-q-005",
    section: "quant",
    type: "problem-solving",
    themes: ["statistics-descriptive"],
    difficulty: "easy",
    text: "The average (arithmetic mean) of five numbers is 12. If one of the numbers is removed, the average of the remaining four numbers is 10. What is the removed number?",
    choices: ["16", "18", "20", "22", "24"],
    correctAnswer: 2,
    explanation: "Sum of 5 numbers = 5 \u00d7 12 = 60. Sum of remaining 4 = 4 \u00d7 10 = 40. The removed number = 60 - 40 = 20.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-q-006",
    section: "quant",
    type: "quantitative-comparison",
    themes: ["exponents-roots"],
    difficulty: "hard",
    text: "Column A: 2^30\nColumn B: 3^20",
    choices: [
      "Column A is greater",
      "Column B is greater",
      "The two quantities are equal",
      "The relationship cannot be determined from the information given",
    ],
    correctAnswer: 1,
    explanation: "Compare 2^30 and 3^20. We can rewrite: 2^30 = (2^3)^10 = 8^10 and 3^20 = (3^2)^10 = 9^10. Since 9 > 8, we have 9^10 > 8^10, so 3^20 > 2^30. Column B is greater.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-q-007",
    section: "quant",
    type: "problem-solving",
    themes: ["coordinate-geometry"],
    difficulty: "medium",
    text: "In the xy-plane, the line passes through the points (1, 3) and (4, 9). What is the y-intercept of this line?",
    choices: ["0", "1", "2", "3", "-1"],
    correctAnswer: 1,
    explanation: "Slope = (9-3)/(4-1) = 6/3 = 2. Using point-slope form with (1,3): y - 3 = 2(x - 1), so y = 2x + 1. The y-intercept is 1.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-q-008",
    section: "quant",
    type: "data-interpretation",
    themes: ["data-interpretation"],
    difficulty: "medium",
    text: "A company's revenue was $200,000 in Year 1, $240,000 in Year 2, and $300,000 in Year 3. What was the approximate percent increase in revenue from Year 1 to Year 3?",
    choices: ["25%", "33%", "40%", "50%", "60%"],
    correctAnswer: 3,
    explanation: "Percent increase = (300,000 - 200,000) / 200,000 \u00d7 100% = 100,000/200,000 \u00d7 100% = 50%.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-q-009",
    section: "quant",
    type: "problem-solving",
    themes: ["fractions-decimals-percents"],
    difficulty: "easy",
    text: "If 40% of a number is 60, what is 25% of the same number?",
    choices: ["37.5", "40", "42.5", "45", "50"],
    correctAnswer: 0,
    explanation: "If 40% of n = 60, then n = 60/0.4 = 150. 25% of 150 = 0.25 \u00d7 150 = 37.5.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-q-010",
    section: "quant",
    type: "problem-solving",
    themes: ["counting-combinatorics"],
    difficulty: "hard",
    text: "In how many ways can 4 people be seated in a row of 6 chairs?",
    choices: ["120", "180", "240", "360", "720"],
    correctAnswer: 3,
    explanation: "This is a permutation: P(6,4) = 6!/(6-4)! = 6!/2! = 720/2 = 360. We choose 4 positions from 6 chairs and arrange people in those positions.",
    source: { name: "Original", type: "original" },
  },
];
