import { Question } from "@/types";

export const greVerbalTCQuestions: Question[] = [
  // ═══════════════════════════════════════════════════════════
  // SINGLE-BLANK TEXT COMPLETION (15 questions: gre-tc-001 – gre-tc-015)
  // ═══════════════════════════════════════════════════════════

  {
    id: "gre-tc-001",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The researcher's findings were so _______ that even her harshest critics were forced to acknowledge the validity of her conclusions.",
    choices: ["compelling", "ambiguous", "derivative", "inconsequential", "speculative"],
    correctAnswer: 0,
    explanation:
      "The sentence indicates findings that convinced even critics, so the word must mean powerfully persuasive. 'Compelling' fits perfectly. 'Ambiguous' (unclear) would not force acknowledgment; 'derivative' (unoriginal) speaks to originality, not persuasiveness; 'inconsequential' (unimportant) contradicts the force described; 'speculative' (conjectural) would invite more skepticism rather than resolve it.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-002",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "easy",
    text: "Although the diplomat was known for her _______ manner, she could be unexpectedly blunt when negotiations stalled.",
    choices: ["tactful", "strident", "brusque", "volatile", "apathetic"],
    correctAnswer: 0,
    explanation:
      "'Although' signals a contrast between the diplomat's usual manner and her bluntness when frustrated. Her normal behavior must be the opposite of blunt, making 'tactful' (showing sensitivity and skill in dealing with others) the correct answer. 'Strident' (harsh/grating), 'brusque' (rudely abrupt), and 'volatile' (unpredictable) do not contrast with bluntness. 'Apathetic' (showing no interest) contrasts with engagement, not with directness.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-003",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single"],
    difficulty: "easy",
    text: "Far from being the _______ process that popular accounts suggest, evolution operates through a complex interplay of random mutation, natural selection, and genetic drift.",
    choices: ["straightforward", "rigorous", "protracted", "imperceptible", "capricious"],
    correctAnswer: 0,
    explanation:
      "'Far from being' signals that the blank must describe what popular accounts wrongly suggest evolution is, which is then contrasted with its actual 'complex interplay.' The blank needs a word meaning simple or uncomplicated: 'straightforward' works. 'Rigorous' (thorough) does not simplify; 'protracted' (lengthy) addresses duration, not complexity; 'imperceptible' (invisible) addresses observability; 'capricious' (unpredictable) actually describes complexity rather than simplicity.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-004",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The author's prose style is notably _______: she favors short, declarative sentences and avoids ornamental language entirely.",
    choices: ["austere", "florid", "labyrinthine", "evocative", "grandiloquent"],
    correctAnswer: 0,
    explanation:
      "The colon signals that the second clause explains the blank. Short, declarative sentences and no ornamental language describe a spare, unadorned style — 'austere' (severely simple). 'Florid' (excessively ornate) and 'grandiloquent' (pompous in language) both describe ornamental styles, the opposite of what is described. 'Labyrinthine' (intricate/complex) contradicts short sentences. 'Evocative' (bringing strong images or feelings) is positive but does not capture the idea of deliberate simplicity.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-005",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The politician's speech was deliberately _______; by avoiding specifics, she ensured that no particular constituency could object to her platform.",
    choices: ["anodyne", "incendiary", "pellucid", "trenchant", "polemical"],
    correctAnswer: 0,
    explanation:
      "The semicolon introduces an explanation: by avoiding specifics, she prevented objections. This describes something intentionally inoffensive and unlikely to provoke. 'Anodyne' (unlikely to provoke or offend) fits precisely. 'Incendiary' (provocative) and 'polemical' (contentious) are the opposite. 'Pellucid' (transparently clear) contradicts vagueness. 'Trenchant' (vigorous and articulate) implies strong expression, which would likely provoke some reaction.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-006",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "medium",
    text: "Paradoxically, the critic's _______ review only increased public interest in the film, as audiences flocked to see what had provoked such extreme censure.",
    choices: ["excoriating", "laudatory", "equivocal", "perfunctory", "dispassionate"],
    correctAnswer: 0,
    explanation:
      "'Paradoxically' signals that the review's effect was the opposite of what one would expect. 'Extreme censure' tells us the review was harshly critical, so the blank must describe a scathing review that, ironically, drew audiences. 'Excoriating' (severely critical) fits. 'Laudatory' (praising) contradicts 'censure.' 'Equivocal' (ambiguous) and 'dispassionate' (objective) do not suggest extreme criticism. 'Perfunctory' (cursory/superficial) would not provoke such extreme reaction.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-007",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single"],
    difficulty: "medium",
    text: "The committee's report, while ostensibly objective, was in fact deeply _______, systematically omitting evidence that contradicted its predetermined conclusions.",
    choices: ["tendentious", "comprehensive", "meticulous", "impartial", "prescient"],
    correctAnswer: 0,
    explanation:
      "'While ostensibly objective ... in fact' sets up a contrast: the report appeared unbiased but was actually biased. 'Systematically omitting evidence that contradicted its conclusions' describes deliberate bias. 'Tendentious' (expressing a strong opinion, especially a controversial one; biased) captures this perfectly. 'Comprehensive' (thorough), 'meticulous' (careful), and 'impartial' (unbiased) all suggest genuine thoroughness or objectivity. 'Prescient' (having foreknowledge) is irrelevant to bias.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-008",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The historian argued that the general's reputation for brilliance was largely _______; his victories, she contended, owed more to his opponents' blunders than to any strategic acumen on his part.",
    choices: ["unmerited", "indubitable", "understated", "perennial", "nascent"],
    correctAnswer: 0,
    explanation:
      "The semicolon introduces the historian's reasoning: his victories came from others' mistakes, not his own skill. This means the reputation is not deserved. 'Unmerited' (not earned or deserved) fits. 'Indubitable' (unquestionable) would affirm the reputation. 'Understated' (presented as less than it is) would suggest he was even more brilliant. 'Perennial' (enduring) and 'nascent' (beginning to develop) describe the reputation's duration, not its legitimacy.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-009",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The novelist's attempt to address themes of social injustice was undermined by her _______ treatment of the very communities she purported to champion, reducing complex individuals to one-dimensional stereotypes.",
    choices: ["reductive", "empathetic", "nuanced", "reverential", "exhaustive"],
    correctAnswer: 0,
    explanation:
      "The sentence explains that the novelist 'reduced complex individuals to one-dimensional stereotypes,' which undermined her social justice aims. The blank must describe this oversimplifying approach. 'Reductive' (tending to present something in an oversimplified form) is an exact match. 'Empathetic' (showing understanding), 'nuanced' (showing subtle distinctions), and 'reverential' (deeply respectful) would all be positive treatments. 'Exhaustive' (comprehensive) implies thoroughness, not oversimplification.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-010",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The scientist's peers considered her work _______: although her experiments were technically flawless, they addressed questions so narrow that their findings had virtually no bearing on the broader field.",
    choices: ["trivial", "groundbreaking", "contentious", "rigorous", "seminal"],
    correctAnswer: 0,
    explanation:
      "The colon introduces an explanation: despite technical excellence, the work addressed questions too narrow to matter. The blank must capture this sense of insignificance. 'Trivial' (of little value or importance) fits. 'Groundbreaking' and 'seminal' (both meaning pioneering) suggest major importance. 'Contentious' (causing disagreement) addresses controversy, not significance. 'Rigorous' (thorough) is actually confirmed by the passage — the experiments were 'technically flawless' — but that's not what peers criticized.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-011",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The philosopher's prose, far from being the _______ thicket of jargon that critics expected, proved surprisingly accessible, rendering even her most abstruse arguments intelligible to lay readers.",
    choices: ["impenetrable", "pellucid", "turgid", "laconic", "mellifluous"],
    correctAnswer: 0,
    explanation:
      "'Far from being ... proved surprisingly accessible' sets up a contrast: critics expected something inaccessible. The metaphor of a 'thicket of jargon' reinforces density and difficulty. 'Impenetrable' (impossible to pass through or understand) fits perfectly with the thicket metaphor and contrasts with 'accessible.' 'Pellucid' (easily understood) is the opposite of what critics feared. 'Turgid' (swollen/pompous) is tempting but describes style, not navigability — and 'turgid thicket' is a mixed metaphor. 'Laconic' (using few words) contradicts 'thicket.' 'Mellifluous' (sweet-sounding) does not relate to comprehensibility.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-012",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single"],
    difficulty: "medium",
    text: "Notwithstanding the professor's _______ in the field of quantum mechanics, her latest paper was met with considerable skepticism by colleagues who found its central premise insufficiently supported by experimental data.",
    choices: ["eminence", "obscurity", "diffidence", "inexperience", "notoriety"],
    correctAnswer: 0,
    explanation:
      "'Notwithstanding' means 'in spite of,' so the blank must describe something that would normally have protected the paper from criticism. The professor's standing should have shielded her, but did not. 'Eminence' (fame and respect within a field) fits: despite her distinguished reputation, colleagues were skeptical. 'Obscurity' (being unknown) and 'inexperience' would make skepticism expected, not surprising. 'Diffidence' (shyness) is irrelevant to whether a paper is taken seriously. 'Notoriety' (fame for something bad) would also make skepticism expected.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-013",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The biographer resisted the temptation to _______ her subject, instead presenting a balanced portrait that acknowledged both his remarkable achievements and his considerable personal failings.",
    choices: ["hagiographize", "excoriate", "caricature", "disregard", "psychoanalyze"],
    correctAnswer: 0,
    explanation:
      "The sentence says the biographer avoided something and 'instead' presented a 'balanced portrait' noting both achievements and failings. The blank must describe an unbalanced, overly positive treatment — since 'achievements' are mentioned alongside 'failings,' the temptation was to ignore the failings and present an idealized portrait. 'Hagiographize' (to write about someone as if they were a saint) fits this one-sided praise perfectly. 'Excoriate' (harshly criticize) is the opposite extreme. 'Caricature' (exaggerate for comic effect) is distortion but not specifically in a positive direction. 'Disregard' (ignore) is too vague. 'Psychoanalyze' addresses method, not imbalance.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-014",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The CEO dismissed the quarterly losses as _______, insisting that the company's long-term strategy remained sound despite what she characterized as transient market turbulence.",
    choices: ["ephemeral", "systemic", "unprecedented", "insuperable", "endemic"],
    correctAnswer: 0,
    explanation:
      "The CEO described the losses as temporary ('transient market turbulence') and maintained that long-term strategy was fine. The blank must align with something fleeting and unimportant in the long run. 'Ephemeral' (lasting a very short time) matches 'transient' perfectly. 'Systemic' (fundamental to the whole system) and 'endemic' (widespread in a particular area) both suggest deep-rooted problems. 'Unprecedented' (never before seen) addresses novelty, not duration. 'Insuperable' (impossible to overcome) suggests permanence, the opposite of what the CEO argued.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-015",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "hard",
    text: "What distinguishes the essayist's work from that of her contemporaries is its resolute refusal to _______: where others traffic in easy certainties, she embraces the provisional and the contingent.",
    choices: ["dogmatize", "equivocate", "innovate", "temporize", "extrapolate"],
    correctAnswer: 0,
    explanation:
      "The colon explains the blank: 'where others traffic in easy certainties, she embraces the provisional and the contingent.' The essayist avoids asserting fixed, absolute positions. 'Dogmatize' (to lay down principles as undeniably true) is exactly what she refuses to do. 'Equivocate' (be deliberately vague) is the opposite — she is not vague but deliberately uncertain. 'Innovate' (introduce new methods) is irrelevant to the certainty/contingency contrast. 'Temporize' (delay to gain time) addresses timing. 'Extrapolate' (extend known data into unknown areas) addresses methodology.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },

  // ═══════════════════════════════════════════════════════════
  // DOUBLE-BLANK TEXT COMPLETION (10 questions: gre-tc-016 – gre-tc-025)
  // ═══════════════════════════════════════════════════════════

  {
    id: "gre-tc-016",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double"],
    difficulty: "medium",
    text: "While the professor's lectures were often (i)_______, his published papers were models of (ii)_______, presenting complex arguments with remarkable economy of expression.",
    choices: [
      "i: prolix",
      "i: terse",
      "i: lucid",
      "ii: concision",
      "ii: verbosity",
      "ii: obscurity",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "'While' signals a contrast between lectures and papers. The papers show 'remarkable economy of expression,' meaning they are concise, so blank (ii) = 'concision.' The contrasting lectures must be the opposite: 'prolix' (excessively wordy). 'Terse' (using few words) would create no contrast with concision. 'Lucid' (clear) contrasts with clarity, not length. For blank (ii), 'verbosity' (wordiness) contradicts 'economy of expression,' and 'obscurity' (unclearness) addresses comprehension rather than length.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-017",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double"],
    difficulty: "medium",
    text: "The documentary was criticized for its (i)_______ approach to a sensitive topic; rather than providing a rigorous investigation, the filmmaker relied on (ii)_______ that oversimplified the issue.",
    choices: [
      "i: superficial",
      "i: meticulous",
      "i: evenhanded",
      "ii: platitudes",
      "ii: statistics",
      "ii: testimonials",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The semicolon introduces an elaboration: 'rather than providing a rigorous investigation' tells us the approach was the opposite of rigorous — 'superficial' (lacking depth). The filmmaker 'oversimplified,' relying on trite, unoriginal expressions: 'platitudes' (remarks that are overused and lack originality). 'Meticulous' (very careful) and 'evenhanded' (fair/balanced) are positive, contradicting the criticism. 'Statistics' would suggest rigor, not oversimplification. 'Testimonials' are firsthand accounts and do not inherently oversimplify.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-018",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double"],
    difficulty: "medium",
    text: "The mayor's decision to reverse her position on the zoning law was seen by supporters as (i)_______, a sign of intellectual flexibility, while opponents characterized it as (ii)_______ that revealed an absence of firm convictions.",
    choices: [
      "i: pragmatic",
      "i: duplicitous",
      "i: inconsequential",
      "ii: vacillation",
      "ii: steadfastness",
      "ii: prescience",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "Supporters viewed the reversal positively ('intellectual flexibility'), so blank (i) must be positive: 'pragmatic' (practical, dealing with things sensibly). 'Duplicitous' (deliberately deceptive) is negative and would not be the supporters' view. 'Inconsequential' (unimportant) contradicts the significance both sides attach to the decision. Opponents saw the reversal negatively ('absence of firm convictions'), so blank (ii) must be negative: 'vacillation' (indecisiveness). 'Steadfastness' (resolute adherence) is positive and contradicts the reversal. 'Prescience' (foreknowledge) does not address conviction.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-019",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double"],
    difficulty: "medium",
    text: "The architect's designs were celebrated for their (i)_______; however, this very quality made them (ii)_______ for builders working with limited budgets and conventional materials.",
    choices: [
      "i: audacity",
      "i: conventionality",
      "i: simplicity",
      "ii: impracticable",
      "ii: indispensable",
      "ii: unremarkable",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "'However' signals a contrast: a celebrated quality created a problem. The designs were praised for boldness ('audacity'), but this same boldness made them difficult for builders with constraints: 'impracticable' (not feasible to implement). 'Conventionality' (being ordinary) would not create builder difficulties. 'Simplicity' would make building easier, not harder. 'Indispensable' (essential) is positive and does not describe a problem. 'Unremarkable' (ordinary) contradicts the notion that these designs are celebrated.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-020",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double"],
    difficulty: "hard",
    text: "The scholar's interpretation of the ancient text was (i)_______, relying on a chain of inferences so tenuous that even sympathetic readers found the argument (ii)_______.",
    choices: [
      "i: speculative",
      "i: orthodox",
      "i: empirical",
      "ii: untenable",
      "ii: incontrovertible",
      "ii: pedestrian",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The sentence describes an interpretation built on 'tenuous' (weak) inferences that even allies could not support. Blank (i) must describe a weakly grounded approach: 'speculative' (based on conjecture rather than evidence). Blank (ii) must describe what sympathetic readers thought of the argument: 'untenable' (not able to be maintained or defended). 'Orthodox' (conventional) contradicts tenuous inferences. 'Empirical' (based on observation) contradicts speculation. 'Incontrovertible' (indisputable) contradicts reader skepticism. 'Pedestrian' (dull/lacking imagination) addresses style, not logical soundness.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-021",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double"],
    difficulty: "hard",
    text: "The novelist's early works displayed a (i)_______ sensibility, one that critics initially found refreshing but that gradually came to seem (ii)_______ as she recycled the same themes without development.",
    choices: [
      "i: distinctive",
      "i: derivative",
      "i: pedestrian",
      "ii: formulaic",
      "ii: avant-garde",
      "ii: ineffable",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "Critics 'initially found refreshing' the early sensibility, so blank (i) must be positive: 'distinctive' (characteristic and unique). 'Derivative' (imitative) and 'pedestrian' (dull) would not be refreshing. Over time, as she recycled themes 'without development,' the same approach became stale: 'formulaic' (produced according to a rigid pattern) captures this deterioration from fresh to repetitive. 'Avant-garde' (experimental/innovative) suggests continued freshness. 'Ineffable' (indescribable) does not convey staleness.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-022",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double"],
    difficulty: "hard",
    text: "The senator's rhetoric, once noted for its (i)_______, had become increasingly (ii)_______; where she had previously marshaled evidence and logic, she now resorted to emotional appeals and ad hominem attacks.",
    choices: [
      "i: cogency",
      "i: bombast",
      "i: opacity",
      "ii: demagogic",
      "ii: judicious",
      "ii: recondite",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The sentence contrasts her past rhetoric ('evidence and logic') with her current approach ('emotional appeals and ad hominem attacks'). Her earlier style, based on evidence and logic, was characterized by 'cogency' (clarity and persuasiveness of argument). Her current style, relying on emotion and personal attacks, is 'demagogic' (appealing to emotions and prejudices rather than reason). 'Bombast' (pompous language) and 'opacity' (obscurity) are negative qualities that would not create a clear 'decline' narrative. 'Judicious' (showing good judgment) contradicts the current deterioration. 'Recondite' (abstruse/obscure) addresses difficulty, not demagoguery.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-023",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double"],
    difficulty: "hard",
    text: "The composer's late quartets are often described as (i)_______; listeners accustomed to the (ii)_______ harmonies of his earlier work frequently find these pieces dissonant and bewildering.",
    choices: [
      "i: forbidding",
      "i: mellifluous",
      "i: derivative",
      "ii: dulcet",
      "ii: astringent",
      "ii: cacophonous",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "Listeners find the late quartets 'dissonant and bewildering,' so blank (i) must describe works that are daunting or off-putting: 'forbidding' (unfriendly or threatening in appearance). The earlier work is contrasted with this dissonance — listeners are 'accustomed to' something pleasant, so blank (ii) = 'dulcet' (sweet-sounding). 'Mellifluous' (sweet-sounding) for blank (i) contradicts 'dissonant.' 'Derivative' (unoriginal) does not explain bewilderment. 'Astringent' (harsh) and 'cacophonous' (harsh-sounding) for blank (ii) would not contrast with the late quartets' dissonance.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-024",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double"],
    difficulty: "medium",
    text: "Although the expedition was widely considered a (i)_______, the team's meticulous field notes proved (ii)_______, providing the foundation for three decades of subsequent research in the region.",
    choices: [
      "i: debacle",
      "i: triumph",
      "i: redundancy",
      "ii: invaluable",
      "ii: negligible",
      "ii: contentious",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "'Although' signals contrast: the expedition was considered negative, but something positive came from it. The field notes 'provided the foundation for three decades of research,' so blank (ii) = 'invaluable' (extremely useful). Given this positive outcome contrasts with the expedition's reputation, blank (i) must be negative: 'debacle' (a sudden and complete disaster). 'Triumph' (great success) would not create a contrast with positive outcomes. 'Redundancy' (being superfluous) does not describe an expedition's failure. 'Negligible' (insignificant) and 'contentious' (controversial) for blank (ii) do not capture the notes' enormous positive impact.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-025",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double"],
    difficulty: "medium",
    text: "The professor's teaching style was simultaneously (i)_______ and (ii)_______: students found his lectures intellectually demanding yet remarkably clear, a rare combination in a field notorious for its opacity.",
    choices: [
      "i: rigorous",
      "i: haphazard",
      "i: rudimentary",
      "ii: lucid",
      "ii: abstruse",
      "ii: soporific",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The colon explains the two qualities: 'intellectually demanding' maps to blank (i) and 'remarkably clear' maps to blank (ii). 'Rigorous' (extremely thorough and careful) matches 'intellectually demanding.' 'Lucid' (expressed clearly) matches 'remarkably clear.' 'Haphazard' (lacking order) and 'rudimentary' (basic) do not mean demanding. 'Abstruse' (difficult to understand) is the opposite of clear. 'Soporific' (inducing sleep) is the opposite of engaging.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },

  // ═══════════════════════════════════════════════════════════
  // TRIPLE-BLANK TEXT COMPLETION (5 questions: gre-tc-026 – gre-tc-030)
  // ═══════════════════════════════════════════════════════════

  {
    id: "gre-tc-026",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The author's magnum opus was (i)_______ in its scope, attempting to synthesize insights from biology, philosophy, and linguistics into a unified theory of human cognition. Critics, however, argued that this very (ii)_______ rendered the work (iii)_______: by trying to encompass so much, the author inevitably sacrificed depth for breadth.",
    choices: [
      "i: ambitious",
      "i: modest",
      "i: derivative",
      "ii: expansiveness",
      "ii: parsimony",
      "ii: originality",
      "iii: superficial",
      "iii: indispensable",
      "iii: prescient",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The work attempts to synthesize multiple fields into a unified theory — this is 'ambitious' (blank i). Critics argued that this broad scope ('expansiveness,' blank ii) caused a problem: 'sacrificed depth for breadth' means the work became 'superficial' (blank iii, lacking depth). 'Modest' and 'derivative' contradict the grand, synthesizing scope. 'Parsimony' (economy) is the opposite of expansiveness. 'Originality' does not cause the depth-vs-breadth problem described. 'Indispensable' (essential) and 'prescient' (foreseeing the future) are positive assessments that contradict the critics' complaint.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-027",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The prime minister's address was a masterwork of political (i)_______: while appearing to (ii)_______ the opposition's concerns about fiscal policy, she actually committed to nothing, ensuring that her government retained complete (iii)_______ to act as circumstances dictated.",
    choices: [
      "i: equivocation",
      "i: candor",
      "i: intransigence",
      "ii: acknowledge",
      "ii: dismiss",
      "ii: exaggerate",
      "iii: latitude",
      "iii: accountability",
      "iii: transparency",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The prime minister 'appeared to' do one thing but 'actually committed to nothing' — this deliberate ambiguity is 'equivocation' (blank i, using ambiguous language to conceal the truth). She seemed to 'acknowledge' (blank ii) the opposition's concerns (the word 'appearing to' shows this was only surface-level). By committing to nothing, she preserved her freedom to act later: 'latitude' (blank iii, freedom of action). 'Candor' (frankness) contradicts evasiveness. 'Intransigence' (stubbornness) contradicts the appearance of engagement. 'Dismiss' and 'exaggerate' would not create the illusion of engagement. 'Accountability' (responsibility) and 'transparency' (openness) both contradict the deliberate obfuscation described.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-028",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "Despite the playwright's (i)_______ reputation — she was known for works that audiences found bleak and unsettling — her final play was unexpectedly (ii)_______, concluding with an act of reconciliation so genuine that even the most (iii)_______ theatergoers left the performance visibly moved.",
    choices: [
      "i: misanthropic",
      "i: sanguine",
      "i: whimsical",
      "ii: affirming",
      "ii: harrowing",
      "ii: inscrutable",
      "iii: jaded",
      "iii: impressionable",
      "iii: effusive",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The playwright was known for 'bleak and unsettling' works, suggesting a dark, people-distrusting worldview: 'misanthropic' (blank i, having a dislike of humankind). 'Despite' signals that the final play broke from this pattern: it concluded with 'genuine reconciliation,' making it 'affirming' (blank ii, emotionally positive and supportive). Even the most hardened, difficult-to-impress audience members were moved: 'jaded' (blank iii, tired and lacking enthusiasm from overexposure). 'Sanguine' (optimistic) and 'whimsical' (playfully quaint) contradict 'bleak.' 'Harrowing' (distressing) does not contrast with her reputation. 'Inscrutable' (mysterious) does not relate to the emotional impact described. 'Impressionable' (easily influenced) is the opposite of hard to move. 'Effusive' (expressing feelings freely) does not indicate resistance to being moved.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-029",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The scientist's methodology was (i)_______: she (ii)_______ established protocols in favor of improvised procedures, a practice that her detractors called reckless but that she defended as necessary for investigating phenomena too (iii)_______ to be captured by standardized approaches.",
    choices: [
      "i: unorthodox",
      "i: rigorous",
      "i: antiquated",
      "ii: eschewed",
      "ii: championed",
      "ii: refined",
      "iii: mercurial",
      "iii: mundane",
      "iii: conspicuous",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The colon introduces an explanation of the methodology: she abandoned established protocols for improvised ones, and detractors called this 'reckless.' This describes an unconventional approach: 'unorthodox' (blank i). She set aside established protocols: 'eschewed' (blank ii, deliberately avoided or kept away from). She argued the phenomena were too changeable for fixed methods: 'mercurial' (blank iii, subject to sudden or unpredictable changes). 'Rigorous' (strict/careful) contradicts improvisation. 'Antiquated' (old-fashioned) does not capture unconventionality in this context. 'Championed' (supported) is the opposite of avoiding protocols. 'Refined' (improved) does not mean abandoned. 'Mundane' (ordinary) would make standardized approaches seem adequate. 'Conspicuous' (clearly visible) does not explain why standard methods fail.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-030",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The essayist's style is characterized by a seeming (i)_______ that belies the meticulous craftsmanship underlying each sentence; what reads as (ii)_______ prose is in fact the product of painstaking revision, every word chosen to create an impression of (iii)_______ that only the most discerning readers recognize as artfully constructed.",
    choices: [
      "i: artlessness",
      "i: pomposity",
      "i: verbosity",
      "ii: effortless",
      "ii: labored",
      "ii: ornate",
      "iii: spontaneity",
      "iii: erudition",
      "iii: formality",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The central paradox is that apparent naturalness conceals deliberate craft. The style seems uncrafted: 'artlessness' (blank i, the quality of being natural and unpretentious). 'Belies' confirms this appearance is deceptive. The prose appears easy and natural: 'effortless' (blank ii). The impression the writer creates through revision is one of natural, unplanned expression: 'spontaneity' (blank iii, the quality of being natural rather than planned). 'Pomposity' (self-importance) and 'verbosity' (wordiness) do not suggest hidden craft. 'Labored' (showing obvious effort) and 'ornate' (elaborately decorated) would not need to 'belie' craftsmanship — they openly display it. 'Erudition' (deep learning) and 'formality' (rigid adherence to convention) do not capture the natural, unforced quality described.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
];
