import { Question } from "@/types";

export const greVerbalSEExpandedQuestions: Question[] = [
  // ─── EASY (6 questions) ─────────────────────────────────────────────
  {
    id: "gre-se-exp-001",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The researcher's conclusions were surprisingly _______, given the complexity of the data she had to interpret.",
    choices: ["straightforward", "contentious", "unambiguous", "tentative", "revolutionary", "obscure"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The word 'surprisingly' combined with 'complexity of the data' suggests the conclusions were unexpectedly clear and simple. Both 'straightforward' (uncomplicated, easy to understand) and 'unambiguous' (not open to more than one interpretation) produce equivalent sentences describing clarity that was surprising given the data's complexity. 'Contentious' (causing disagreement) addresses debate, not clarity. 'Tentative' (uncertain, hesitant) is what one might expect from complex data, so it would not be surprising. 'Revolutionary' (involving dramatic change) addresses impact, not clarity. 'Obscure' (not clearly understood) is the opposite of what the sentence requires.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-002",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The young artist's work, though technically accomplished, struck many critics as _______, lacking the personal vision that distinguishes memorable art from mere craft.",
    choices: ["derivative", "provocative", "imitative", "audacious", "visionary", "meticulous"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The work lacks 'personal vision' and is distinguished only by technical skill, suggesting it borrows from others rather than offering something original. Both 'derivative' (imitative of the work of another; not original) and 'imitative' (copying or following a model) produce equivalent sentences describing work that lacks originality. 'Provocative' (stimulating thought) and 'audacious' (showing bold willingness to take risks) suggest strong personal expression. 'Visionary' (thinking about the future with imagination) directly contradicts the lack of personal vision. 'Meticulous' (showing great attention to detail) describes the technical accomplishment already acknowledged.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-003",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The governor's _______ response to the crisis — she waited nearly a week before issuing a public statement — drew sharp criticism from both parties.",
    choices: ["belated", "precipitous", "tardy", "measured", "vigorous", "inflammatory"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The governor waited 'nearly a week' to respond, and this delay 'drew sharp criticism,' indicating the response came too late. Both 'belated' (coming later than should have been the case) and 'tardy' (delaying beyond the expected time; late) produce equivalent sentences describing an unacceptably slow response. 'Precipitous' (done too quickly without adequate thought) and 'vigorous' (strong, active) suggest speed, the opposite of the delay described. 'Measured' (careful and deliberate) has a more neutral or positive connotation and does not capture the criticism. 'Inflammatory' (arousing strong feeling) addresses tone, not timing.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-004",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The editorial's argument was so _______ that even readers who disagreed with its conclusion had to admire the logic of its reasoning.",
    choices: ["cogent", "specious", "compelling", "fallacious", "provocative", "verbose"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "Even opponents admired the argument's logic, indicating it was powerfully persuasive and well-reasoned. Both 'cogent' (clear, logical, and convincing) and 'compelling' (evoking interest or admiration in a powerfully irresistible way) produce equivalent sentences describing an argument that impresses through its logical force. 'Specious' (superficially plausible but actually wrong) and 'fallacious' (based on a fallacy; logically unsound) both describe flawed logic, which opponents would not admire. 'Provocative' (causing thought or discussion) does not specifically address logical quality. 'Verbose' (using too many words) addresses length, not persuasiveness.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-005",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The professor's _______ comments on the student's thesis, though difficult to hear, ultimately helped her strengthen the weakest sections of her argument.",
    choices: ["candid", "flattering", "frank", "evasive", "perfunctory", "laudatory"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The comments were 'difficult to hear' but ultimately helpful, indicating honest, direct criticism. Both 'candid' (truthful and straightforward) and 'frank' (open, honest, and direct) produce equivalent sentences describing feedback that is hard to receive because of its directness but valuable for its truthfulness. 'Flattering' (lavishing praise) and 'laudatory' (expressing praise) would not be difficult to hear. 'Evasive' (avoiding direct confrontation) would not help strengthen weak sections. 'Perfunctory' (carried out without care or interest) would not be helpful enough to improve the thesis.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-006",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The committee's report was _______, running to over three hundred pages and addressing every conceivable objection to the proposed regulation.",
    choices: ["exhaustive", "superficial", "comprehensive", "cursory", "tendentious", "provisional"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The report was over three hundred pages and addressed 'every conceivable objection,' indicating thoroughness. Both 'exhaustive' (examining or including all possibilities; very thorough) and 'comprehensive' (including or dealing with all elements) produce equivalent sentences describing a complete, thorough report. 'Superficial' (existing at the surface; lacking depth) and 'cursory' (hasty and therefore not thorough) are the opposite of what is described. 'Tendentious' (biased, expressing a strong opinion) addresses fairness, not thoroughness. 'Provisional' (temporary, arranged for the present) does not address scope or depth.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },

  // ─── MEDIUM (8 questions) ──────────────────────────────────────────
  {
    id: "gre-se-exp-007",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The anthropologist's fieldwork was notable for its _______ scope; rather than studying a single community, she conducted parallel investigations across four continents over a fifteen-year period.",
    choices: ["expansive", "circumscribed", "sweeping", "parochial", "desultory", "intensive"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The research spanned 'four continents over fifteen years,' indicating enormous breadth. Both 'expansive' (covering a wide area; extensive) and 'sweeping' (wide in range or effect) produce equivalent sentences describing the vast scope of the fieldwork. 'Circumscribed' (restricted within limits) and 'parochial' (having a narrow outlook) are the opposite, suggesting limited scope. 'Desultory' (lacking a plan or purpose; going from one thing to another) suggests randomness, not intentional breadth. 'Intensive' (concentrated on a single area) describes depth rather than breadth.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-008",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "Although the novelist's early reviewers praised her prose as refreshingly direct, later critics found the same quality _______, arguing that her refusal to employ metaphor or allusion impoverished her fiction.",
    choices: ["reductive", "laudable", "simplistic", "evocative", "ornate", "felicitous"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "What early reviewers praised as 'refreshingly direct,' later critics reinterpreted negatively as overly simple and impoverishing. Both 'reductive' (tending to present something in oversimplified terms) and 'simplistic' (treating complex issues as simpler than they really are) produce equivalent sentences where the same directness is seen as a failing. 'Laudable' (deserving praise) would repeat the early reviewers' positive assessment, not offer the later critics' negative one. 'Evocative' (bringing strong images to mind) and 'felicitous' (well-chosen, apt) are positive descriptions of prose. 'Ornate' (elaborately decorated) contradicts 'direct' prose.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-009",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The politician's attempt at humor fell flat; what she intended as lighthearted banter was widely perceived as _______ toward the very constituents she was trying to court.",
    choices: ["condescending", "deferential", "patronizing", "ingratiating", "solicitous", "genial"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The humor 'fell flat' and was directed at people she was trying to win over, suggesting it came across as talking down to them. Both 'condescending' (showing an attitude of patronizing superiority) and 'patronizing' (treating with an apparent kindness that betrays a feeling of superiority) produce equivalent sentences describing an attitude that offends rather than charms. 'Deferential' (showing respect) and 'solicitous' (showing interest or concern) suggest too much deference, not too little. 'Ingratiating' (intended to gain approval) describes the intention, not the unintended effect. 'Genial' (friendly, cheerful) is the effect she intended, not what was perceived.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-010",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The philosopher's writing is often criticized as needlessly _______; she seems to take perverse pleasure in constructing sentences that require multiple readings before yielding their meaning.",
    choices: ["convoluted", "pellucid", "tortuous", "accessible", "didactic", "pithy"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The sentences require 'multiple readings' to understand, and the writer seems to deliberately make them difficult. Both 'convoluted' (extremely complex and difficult to follow) and 'tortuous' (excessively lengthy or complex) produce equivalent sentences describing unnecessarily complicated writing. 'Pellucid' (easily understood) and 'accessible' (easy to understand) are the opposite. 'Didactic' (intended to teach) addresses purpose, not difficulty. 'Pithy' (terse and meaningful) describes concise, clear expression, the opposite of what is described.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-011",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "Despite the company's official commitment to transparency, internal communications revealed a corporate culture that was remarkably _______ about its decision-making processes.",
    choices: ["opaque", "forthright", "secretive", "candid", "punctilious", "cavalier"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "'Despite' signals a contrast between the stated commitment to transparency and the actual practice. The internal communications showed the company hid its decision-making. Both 'opaque' (not transparent; difficult to understand) and 'secretive' (inclined to conceal) produce equivalent sentences describing a lack of openness. 'Forthright' (direct and outspoken) and 'candid' (truthful, straightforward) align with transparency, not its opposite. 'Punctilious' (showing great attention to detail) addresses meticulousness, not secrecy. 'Cavalier' (showing a lack of proper concern) addresses carelessness, not deliberate concealment.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-012",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The biographer wisely avoided the _______ tone that mars so many accounts of the statesman's life, opting instead for a critical perspective that acknowledged his achievements without ignoring his serious ethical lapses.",
    choices: ["hagiographic", "censorious", "reverential", "sardonic", "dispassionate", "polemical"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The biographer avoided an uncritically positive tone in favor of a balanced one that did not 'ignore ethical lapses.' The problematic tone in other accounts must be excessively admiring. Both 'hagiographic' (treating the subject with excessive reverence, as if writing about a saint) and 'reverential' (showing deep respect and admiration) produce equivalent sentences describing the worshipful tone that was avoided. 'Censorious' (severely critical) is the opposite extreme. 'Sardonic' (grimly mocking) is too negative. 'Dispassionate' (not influenced by strong emotion) actually describes a balanced approach, not an excessively positive one. 'Polemical' (involving strongly critical argument) does not describe excessive admiration.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-013",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The diplomat's carefully worded response was a model of _______; she managed to address the journalist's provocative question without either endorsing or repudiating the controversial policy.",
    choices: ["circumlocution", "forthrightness", "evasiveness", "belligerence", "transparency", "magniloquence"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The diplomat neither endorsed nor repudiated the policy, carefully avoiding a direct answer to a provocative question. Both 'circumlocution' (the use of many words where fewer would do, especially to avoid being direct) and 'evasiveness' (tending to avoid commitment or self-revelation) produce equivalent sentences describing the art of not answering directly. 'Forthrightness' (directness, honesty) and 'transparency' (openness) are the opposite of what is described. 'Belligerence' (aggressive hostility) does not describe the careful, measured response. 'Magniloquence' (the use of high-flown language) addresses style, not directness.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-014",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The scientist's peers were troubled by the _______ nature of his claims; he presented as established fact what was, at best, a promising but unverified hypothesis.",
    choices: ["dogmatic", "tentative", "categorical", "equivocal", "diffident", "circumspect"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The scientist presented unverified hypotheses as 'established fact,' showing excessive certainty. Both 'dogmatic' (inclined to lay down principles as undeniably true) and 'categorical' (unambiguously explicit and direct; absolute) produce equivalent sentences describing claims made with inappropriate definitiveness. 'Tentative' (not certain or fixed), 'equivocal' (ambiguous, open to interpretation), 'diffident' (modest, lacking self-confidence), and 'circumspect' (wary, cautious) all describe the opposite quality — hedging or uncertainty — which would not have troubled peers in this context.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },

  // ─── HARD (6 questions) ─────────────────────────────────────────────
  {
    id: "gre-se-exp-015",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The literary critic argued that the novel's apparent formlessness was in fact deeply _______, with every seeming digression carefully orchestrated to reinforce the work's central themes.",
    choices: ["calculated", "haphazard", "deliberate", "spontaneous", "desultory", "impetuous"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The critic sees purposeful design behind what appears random — 'every seeming digression carefully orchestrated.' Both 'calculated' (done with full awareness; planned) and 'deliberate' (done consciously and intentionally) produce equivalent sentences arguing that the apparent disorder is actually purposeful. 'Haphazard' (lacking any obvious principle of organization) and 'desultory' (lacking a plan or purpose) would confirm, rather than challenge, the impression of formlessness. 'Spontaneous' (performed without premeditation) and 'impetuous' (acting quickly without thought) both suggest unplanned action, contradicting the 'carefully orchestrated' digressions.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-016",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The historian's treatment of the revolutionary period was notably _______, presenting the perspectives of peasants, merchants, and aristocrats with equal seriousness and refusing to cast any group as either hero or villain.",
    choices: ["evenhanded", "partisan", "disinterested", "tendentious", "hagiographic", "polemical"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The historian presents 'all perspectives with equal seriousness' and refuses to assign moral roles, indicating fairness and impartiality. Both 'evenhanded' (fair and impartial in treatment) and 'disinterested' (not influenced by considerations of personal advantage; impartial) produce equivalent sentences describing a balanced approach. Note that 'disinterested' means 'impartial,' not 'uninterested.' 'Partisan' (prejudiced in favor of a particular cause) and 'tendentious' (expressing a strong opinion) both describe biased treatments. 'Hagiographic' (treating a subject with undue reverence) would cast one group as heroes. 'Polemical' (involving strongly critical argument) would assign blame.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-017",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The composer's new symphony was _______ in its emotional range, moving from passages of almost unbearable grief to moments of transcendent joy within a single movement.",
    choices: ["capacious", "monochromatic", "expansive", "austere", "uniform", "restrained"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The symphony moves from 'unbearable grief' to 'transcendent joy,' demonstrating enormous emotional breadth. Both 'capacious' (having a lot of space inside; roomy — used figuratively for range) and 'expansive' (covering a wide area or range; extensive) produce equivalent sentences describing the vast emotional territory the work covers. 'Monochromatic' (containing only one color; lacking variety) and 'uniform' (not changing; the same throughout) are the opposite of this emotional variety. 'Austere' (severely simple, without adornment) and 'restrained' (characterized by reserve or moderation) both suggest limited emotional expression, contradicting the passage from grief to joy.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-018",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The essayist's tone is best described as _______, combining sharp social observation with a pervasive sense that human folly, though lamentable, is ultimately beyond remedy.",
    choices: ["mordant", "sanguine", "sardonic", "ebullient", "mawkish", "didactic"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The essayist offers 'sharp social observation' — meaning biting criticism — combined with a resigned view that human foolishness cannot be fixed. Both 'mordant' (having a sharp, biting quality; incisive) and 'sardonic' (grimly mocking or cynical) produce equivalent sentences describing this combination of sharp wit and dark resignation. 'Sanguine' (optimistic, especially in difficult situations) and 'ebullient' (full of cheerful enthusiasm) are too positive for someone who sees human folly as beyond remedy. 'Mawkish' (sentimental in a feeble way) does not describe sharp observation. 'Didactic' (intended to teach a moral lesson) implies the writer believes in improvement, contradicting the view that folly is irremediable.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-019",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The philosopher's ethical framework was _______ in the sense that it offered no fixed rules but instead demanded that moral agents assess each situation anew, weighing competing obligations without recourse to predetermined hierarchies of value.",
    choices: ["situational", "absolutist", "contextual", "dogmatic", "codified", "prescriptive"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The framework offers 'no fixed rules' and requires assessing 'each situation anew' without 'predetermined hierarchies,' meaning ethical judgment depends on specific circumstances. Both 'situational' (relating to or dependent on circumstances) and 'contextual' (dependent on the context) produce equivalent sentences describing an ethics that varies by situation. 'Absolutist' (holding that a principle is unconditionally valid) and 'dogmatic' (inclined to lay down principles as undeniably true) both describe fixed-rule systems, the opposite of what is described. 'Codified' (arranged into a systematic code) suggests established rules. 'Prescriptive' (relating to the imposition of rules) also implies predetermined guidance.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-exp-020",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The geologist cautioned that the current period of seismic calm was almost certainly _______, noting that the region's tectonic history suggested a major earthquake was not a matter of if but when.",
    choices: ["transient", "permanent", "evanescent", "enduring", "salutary", "anomalous"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The geologist warns that the seismic calm will not last, since a major earthquake is expected. Both 'transient' (lasting only for a short time; impermanent) and 'evanescent' (soon passing out of sight, memory, or existence; quickly fading) produce equivalent sentences describing a temporary calm before inevitable seismic activity. 'Permanent' (lasting forever) and 'enduring' (lasting over time) are the opposite of the warning being issued. 'Salutary' (producing good effects; beneficial) describes the quality of the calm rather than its duration. 'Anomalous' (deviating from the norm) is tempting because the calm could be seen as unusual, but it does not form a synonym pair with any other choice and does not specifically address the temporary nature that the sentence emphasizes.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
];
