import { Question } from "@/types";

export const greVerbalTCExpandedQuestions: Question[] = [
  // ═══════════════════════════════════════════════════════════
  // SINGLE-BLANK TEXT COMPLETION (10 questions: gre-tc-exp-001 – gre-tc-exp-010)
  // ═══════════════════════════════════════════════════════════

  {
    id: "gre-tc-exp-001",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The novelist's reputation rests largely on her ability to render the _______ details of everyday life with such precision that mundane domestic scenes acquire an almost luminous significance.",
    choices: ["prosaic", "fantastical", "harrowing", "enigmatic", "grandiose"],
    correctAnswer: 0,
    explanation:
      "The sentence describes how the novelist transforms ordinary, everyday details into something meaningful. 'Prosaic' (lacking poetic beauty; commonplace) fits perfectly because the point is that she elevates the ordinary. 'Fantastical' (imaginative, remote from reality) contradicts 'everyday life.' 'Harrowing' (acutely distressing) is too extreme for 'mundane domestic scenes.' 'Enigmatic' (mysterious) contradicts the emphasis on clear, precise rendering. 'Grandiose' (impressive, imposing) contradicts the emphasis on the everyday and mundane.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-exp-002",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "easy",
    text: "Although the archaeological evidence was _______, the researchers cautiously advanced a hypothesis, acknowledging that future excavations might overturn their conclusions entirely.",
    choices: ["fragmentary", "overwhelming", "fabricated", "redundant", "unambiguous"],
    correctAnswer: 0,
    explanation:
      "The researchers were 'cautious' and admitted future findings might 'overturn their conclusions,' indicating the evidence was incomplete. 'Fragmentary' (consisting of small, disconnected parts; incomplete) fits this context of limited evidence. 'Overwhelming' (very great in amount) and 'unambiguous' (clear) would justify confidence, not caution. 'Fabricated' (invented, false) would discredit the research entirely, not merely warrant caution. 'Redundant' (no longer needed; superfluous) does not describe the quality of evidence.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-exp-003",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The lecturer's _______ delivery, characterized by a monotonous tone and a refusal to deviate from her prepared notes, did little to inspire enthusiasm among the students in the auditorium.",
    choices: ["pedestrian", "electrifying", "improvisational", "provocative", "mellifluous"],
    correctAnswer: 0,
    explanation:
      "A 'monotonous tone' and rigid adherence to notes that failed to 'inspire enthusiasm' describe a dull, uninspired presentation. 'Pedestrian' (lacking imagination or excitement; dull) captures this precisely. 'Electrifying' (thrilling) and 'provocative' (stimulating thought or interest) both suggest an engaging delivery. 'Improvisational' (created spontaneously) contradicts 'refusal to deviate from her prepared notes.' 'Mellifluous' (sweet-sounding) describes vocal quality, not engagement, and would not cause a lack of enthusiasm.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-exp-004",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The biologist's findings _______ the long-held assumption that the species was solitary; her fieldwork revealed complex social hierarchies and cooperative behaviors never before documented.",
    choices: ["corroborated", "adumbrated", "belied", "perpetuated", "rationalized"],
    correctAnswer: 2,
    explanation:
      "The fieldwork revealed 'complex social hierarchies and cooperative behaviors,' directly contradicting the assumption that the species was solitary. 'Belied' (failed to give a true impression of; contradicted) fits perfectly. 'Corroborated' (confirmed or gave support to) is the opposite — it would mean the findings supported the assumption. 'Adumbrated' (foreshadowed or outlined) does not convey contradiction. 'Perpetuated' (caused to continue) would mean the findings reinforced the old view. 'Rationalized' (attempted to explain or justify) does not capture the act of disproving.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-exp-005",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "medium",
    text: "Despite her _______ manner at the podium, the senator was known among her staff for a biting wit and an acerbic sense of humor that she reserved for private conversations.",
    choices: ["decorous", "sardonic", "irascible", "flippant", "boorish"],
    correctAnswer: 0,
    explanation:
      "'Despite' signals a contrast between the senator's public behavior and her private personality. Privately she was sharp and 'acerbic,' so publicly she must appear the opposite: restrained and proper. 'Decorous' (dignified and in good taste; proper) creates this contrast effectively. 'Sardonic' (grimly mocking) aligns with, rather than contrasts with, her private wit. 'Irascible' (easily angered) and 'boorish' (rough and bad-mannered) are both negative qualities that do not contrast with acerbic humor. 'Flippant' (not showing proper respect or seriousness) is closer to her private self than her public image.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-exp-006",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The philosopher's argument was ingenious but ultimately _______; it relied on a distinction so fine that in practice it dissolved, leaving the two positions it sought to differentiate effectively indistinguishable.",
    choices: ["untenable", "cogent", "prescient", "hackneyed", "inflammatory"],
    correctAnswer: 0,
    explanation:
      "The argument's central distinction 'dissolved' in practice, making the two positions 'indistinguishable' — the argument cannot hold up under scrutiny. 'Untenable' (not able to be maintained or defended) captures this collapse of the argument despite its cleverness. 'Cogent' (clear, logical, convincing) contradicts the failure described. 'Prescient' (having foreknowledge) addresses foresight, not logical soundness. 'Hackneyed' (lacking significance through overuse) addresses originality, which contradicts 'ingenious.' 'Inflammatory' (arousing strong feeling) addresses emotional impact, not logical viability.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-exp-007",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The diplomat's memoirs are remarkable less for their revelations — she is notably _______ about her most consequential decisions — than for the vivid portraits they paint of the world leaders she encountered.",
    choices: ["reticent", "forthcoming", "voluble", "didactic", "hyperbolic"],
    correctAnswer: 0,
    explanation:
      "The memoirs are remarkable not for revelations but for portraits, and the dash explains why: she does not say much about key decisions. 'Reticent' (not revealing one's thoughts or feelings readily; reserved) fits this withholding of information. 'Forthcoming' (willing to divulge information) and 'voluble' (speaking fluently and at length) both suggest she would share revelations freely. 'Didactic' (intended to teach) addresses purpose, not disclosure. 'Hyperbolic' (exaggerated) addresses truthfulness, not the amount of disclosure.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-exp-008",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The critic's review was a study in _______: every compliment was so hedged with qualifications and provisos that the cumulative effect was less one of praise than of meticulous, almost surgical, disparagement.",
    choices: ["equivocation", "adulation", "invective", "magnanimity", "prolixity"],
    correctAnswer: 0,
    explanation:
      "The review appeared to praise but actually disparaged through heavy qualification — every compliment was undercut by caveats. 'Equivocation' (the use of ambiguous language to conceal the truth or avoid committing oneself) captures this technique of seeming to say one thing while meaning another. 'Adulation' (excessive admiration) contradicts the actual effect of disparagement. 'Invective' (insulting, abusive language) is too direct — the critic was indirect. 'Magnanimity' (generosity of spirit) contradicts the surgical disparagement. 'Prolixity' (excessive wordiness) addresses length, not the technique of qualified praise.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-exp-009",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "hard",
    text: "What critics mistake for ideological _______ in the historian's work is actually a principled commitment to following evidence wherever it leads, even when doing so produces conclusions that sit uncomfortably with any single political framework.",
    choices: ["inconsistency", "rigidity", "transparency", "partisanship", "acuity"],
    correctAnswer: 0,
    explanation:
      "The historian's conclusions do not align with 'any single political framework,' which critics misread as a flaw. The sentence structure ('What critics mistake for X is actually Y') tells us X is a negative quality that the historian does not actually possess. Reaching conclusions that defy any single framework would look like changing positions — 'inconsistency' (lack of steady adherence to the same principles). 'Rigidity' (inflexibility) is the opposite of what conclusions spanning multiple frameworks would suggest. 'Transparency' (openness) is not typically a criticism. 'Partisanship' (prejudice in favor of one cause) is precisely what the historian avoids, and her work would not be mistaken for it. 'Acuity' (sharpness of thought) is positive and unlikely to be a misperception.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },
  {
    id: "gre-tc-exp-010",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The sociologist argued that the apparent _______ of the neighborhood — its tidy lawns, uniform facades, and quiet streets — masked a deeply fractured community in which residents maintained an elaborate pretense of harmony while harboring profound mutual distrust.",
    choices: ["placidity", "squalor", "heterogeneity", "vibrancy", "austerity"],
    correctAnswer: 0,
    explanation:
      "The neighborhood's outward appearance — 'tidy lawns, uniform facades, quiet streets' — conceals inner dysfunction. The blank must describe this calm, peaceful surface. 'Placidity' (the quality of being calm and peaceful) matches the serene exterior that masks turmoil. 'Squalor' (dirty, unpleasant conditions) contradicts the tidy description. 'Heterogeneity' (diversity) contradicts 'uniform facades.' 'Vibrancy' (full of energy and life) contradicts 'quiet streets.' 'Austerity' (severe simplicity) partially fits the description but does not capture the calm, harmonious facade that specifically contrasts with hidden distrust.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
  },

  // ═══════════════════════════════════════════════════════════
  // DOUBLE-BLANK TEXT COMPLETION (10 questions: gre-tc-exp-011 – gre-tc-exp-020)
  // ═══════════════════════════════════════════════════════════

  {
    id: "gre-tc-exp-011",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The ambassador's speech was deliberately (i)_______, designed to reassure anxious allies without making any (ii)_______ that might later constrain the administration's options.",
    choices: [
      "i: vague",
      "i: bellicose",
      "i: meticulous",
      "ii: commitments",
      "ii: accusations",
      "ii: concessions",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The speech was designed to 'reassure' without 'constraining options,' meaning it was intentionally unspecific to avoid binding promises. Blank (i) = 'vague' (not clearly expressed). Blank (ii) = 'commitments' (pledges that would limit future action). 'Bellicose' (warlike) would not reassure allies. 'Meticulous' (careful, precise) contradicts deliberate vagueness. 'Accusations' would not reassure anyone. 'Concessions' (things yielded) might constrain options, but the sentence emphasizes reassurance without specifics, and 'commitments' fits the logic of preserving flexibility more precisely.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-exp-012",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The museum's new exhibition has been praised for its (i)_______ presentation of a notoriously complex period in history; curators managed to make the material (ii)_______ without sacrificing scholarly rigor.",
    choices: [
      "i: accessible",
      "i: arcane",
      "i: tendentious",
      "ii: engaging",
      "ii: abstruse",
      "ii: contentious",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The curators made complex material understandable 'without sacrificing scholarly rigor,' earning praise. Blank (i) = 'accessible' (easy to understand or appreciate). Blank (ii) = 'engaging' (attracting interest). 'Arcane' (mysterious, known by few) is the opposite of accessible and would not be praised in this context. 'Tendentious' (biased) contradicts scholarly rigor. 'Abstruse' (hard to understand) is the opposite of what the curators achieved. 'Contentious' (causing disagreement) does not relate to making material approachable.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-exp-013",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The playwright's early comedies, once dismissed as (i)_______ entertainments unworthy of serious critical attention, have been reassessed by a new generation of scholars who find in them a (ii)_______ commentary on class and power that earlier critics entirely overlooked.",
    choices: [
      "i: frivolous",
      "i: subversive",
      "i: canonical",
      "ii: trenchant",
      "ii: tepid",
      "ii: derivative",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The comedies were originally dismissed as lightweight, 'unworthy of serious critical attention' — 'frivolous' (not having any serious purpose or value) captures this dismissal. New scholars discovered a sharp social critique hidden within them: 'trenchant' (vigorous, incisive, effective) describes this penetrating commentary on class and power. 'Subversive' (seeking to undermine) for blank (i) is tempting but would not lead to a dismissal as 'unworthy of serious attention.' 'Canonical' (accepted as authoritative) contradicts being dismissed. 'Tepid' (lukewarm, lacking conviction) and 'derivative' (imitative, unoriginal) do not describe the kind of sharp commentary that warrants scholarly reassessment.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-exp-014",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The philosopher's prose, though often praised for its (i)_______, can also be a liability; her sentences are so tightly compressed that readers must (ii)_______ every clause to extract the full meaning, making even brief passages demand sustained concentration.",
    choices: [
      "i: density",
      "i: transparency",
      "i: elegance",
      "ii: unpack",
      "ii: skim",
      "ii: paraphrase",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The philosopher's sentences are 'tightly compressed' and demand 'sustained concentration,' indicating that her writing packs much meaning into few words. Blank (i) = 'density' (the quality of being closely compacted; richness of content). This quality is both praised and a 'liability.' Blank (ii) = 'unpack' (to analyze in detail), since readers must carefully decompress each tightly compressed clause. 'Transparency' (clarity) would not create the difficulty described. 'Elegance' (grace, beauty of style) does not capture compression. 'Skim' (read quickly) is the opposite of what the dense prose requires. 'Paraphrase' (restate in simpler terms) is a possible response to difficulty but does not capture the clause-by-clause analytical work the sentence describes.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-exp-015",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double", "vocabulary-in-context"],
    difficulty: "medium",
    text: "Although the governor presented her economic plan as (i)_______, independent analysts noted that it drew heavily on proposals that had been circulating in policy circles for decades, suggesting that the plan's true virtue lay not in novelty but in the political (ii)_______ needed to finally implement long-discussed reforms.",
    choices: [
      "i: groundbreaking",
      "i: provisional",
      "i: contentious",
      "ii: will",
      "ii: naivety",
      "ii: ambiguity",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The governor claimed novelty for her plan, but analysts showed the ideas had existed for decades. Blank (i) = 'groundbreaking' (innovative, pioneering) — the governor's claim that is undermined by the analysis. The plan's actual merit was the determination to implement old ideas: blank (ii) = 'will' (the determination to achieve something). 'Provisional' (temporary) does not claim novelty. 'Contentious' (controversial) addresses debate, not innovation. 'Naivety' (lack of experience or judgment) would be critical, not virtuous. 'Ambiguity' (uncertainty) contradicts the idea of decisive implementation.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-exp-016",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The literary critic's reading of the poem was provocatively (i)_______, attributing to the poet intentions that most scholars would consider (ii)_______ given the scant biographical evidence available.",
    choices: [
      "i: conjectural",
      "i: orthodox",
      "i: meticulous",
      "ii: unwarranted",
      "ii: self-evident",
      "ii: commendable",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The critic attributed specific intentions to the poet despite 'scant biographical evidence,' making the interpretation speculative. Blank (i) = 'conjectural' (based on incomplete information; speculative). Most scholars would view such attributions as unjustified given the thin evidence: blank (ii) = 'unwarranted' (not justified or authorized). 'Orthodox' (conforming to accepted views) contradicts 'provocatively.' 'Meticulous' (showing great attention to detail) suggests careful work, but the issue is insufficient evidence, not carelessness. 'Self-evident' (needing no proof) contradicts the scant evidence problem. 'Commendable' (worthy of praise) contradicts the scholarly skepticism.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-exp-017",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The composer's late symphonies resist easy categorization; they are neither the (i)_______ works of a master resting on past achievements nor the radical experiments of an iconoclast, but rather occupy an unsettled middle ground that reflects a deeply (ii)_______ artistic temperament.",
    choices: [
      "i: complacent",
      "i: audacious",
      "i: rudimentary",
      "ii: restive",
      "ii: placid",
      "ii: dogmatic",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The symphonies are described as existing between two extremes: safe repetition and radical experimentation. The first extreme is a master 'resting on past achievements,' producing works that are self-satisfied and unambitious: 'complacent' (showing smug or uncritical satisfaction). The 'unsettled middle ground' suggests an artist who is restlessly searching rather than at ease: 'restive' (unable to keep still or be content; uneasy). 'Audacious' (bold, daring) aligns with the iconoclast extreme, not the complacent one. 'Rudimentary' (basic, undeveloped) does not describe a master's safe work. 'Placid' (calm, peaceful) contradicts 'unsettled.' 'Dogmatic' (inclined to lay down principles as undeniable) does not capture artistic unease.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-exp-018",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The sociologist's thesis was (i)_______ in conception — few would dispute the importance of examining how economic inequality affects democratic participation — but its execution was marred by a (ii)_______ methodology that failed to account for numerous confounding variables.",
    choices: [
      "i: laudable",
      "i: pedestrian",
      "i: quixotic",
      "ii: slipshod",
      "ii: rigorous",
      "ii: innovative",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The thesis had a good idea but poor execution. The topic's importance is affirmed ('few would dispute'), so the conception was praiseworthy: blank (i) = 'laudable' (deserving praise and commendation). The execution 'failed to account for confounding variables,' indicating careless methods: blank (ii) = 'slipshod' (characterized by a lack of care, thought, or organization). 'Pedestrian' (dull, ordinary) contradicts the acknowledged importance of the topic. 'Quixotic' (exceedingly idealistic, unrealistic) would undermine the acknowledged value. 'Rigorous' (extremely thorough and careful) contradicts the methodological failures. 'Innovative' (featuring new methods) does not address the failure to control for variables.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-exp-019",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double", "vocabulary-in-context"],
    difficulty: "hard",
    text: "Historians have long debated whether the general's decision to retreat was an act of (i)_______, preserving his forces for a decisive future engagement, or an act of (ii)_______ that squandered a fleeting opportunity for victory.",
    choices: [
      "i: prudence",
      "i: belligerence",
      "i: caprice",
      "ii: pusillanimity",
      "ii: sagacity",
      "ii: magnanimity",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The debate presents two opposing interpretations of the retreat. The positive interpretation — 'preserving forces for a decisive future engagement' — describes wise caution: blank (i) = 'prudence' (acting with care and thought for the future). The negative interpretation — 'squandered a fleeting opportunity' — describes timid cowardice: blank (ii) = 'pusillanimity' (showing a lack of courage; timidity). 'Belligerence' (aggressive hostility) contradicts retreating. 'Caprice' (sudden, unaccountable change of behavior) does not describe strategic preservation of forces. 'Sagacity' (keen mental discernment) is positive, not negative. 'Magnanimity' (generosity toward a rival) does not relate to military retreat.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-tc-exp-020",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The essayist's celebrated (i)_______ — her ability to move seamlessly between personal anecdote, historical analysis, and philosophical meditation — is precisely what makes her work so difficult to (ii)_______; no single generic category can contain such formally restless writing.",
    choices: [
      "i: versatility",
      "i: prolixity",
      "i: austerity",
      "ii: classify",
      "ii: appreciate",
      "ii: disseminate",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The essayist moves 'seamlessly between' multiple modes of writing, demonstrating range and flexibility: blank (i) = 'versatility' (the ability to adapt to many different functions or activities). This range means 'no single generic category can contain' the work, making it hard to place in a category: blank (ii) = 'classify' (to arrange in categories). 'Prolixity' (using too many words) addresses length, not range. 'Austerity' (severe simplicity) contradicts the richness of multiple modes. 'Appreciate' (recognize the value of) does not follow from formal restlessness. 'Disseminate' (spread widely) addresses distribution, not categorization.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },

  // ═══════════════════════════════════════════════════════════
  // TRIPLE-BLANK TEXT COMPLETION (10 questions: gre-tc-exp-021 – gre-tc-exp-030)
  // ═══════════════════════════════════════════════════════════

  {
    id: "gre-tc-exp-021",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "medium",
    text: "The governor's proposed legislation was (i)_______ in its aims, seeking to address poverty, healthcare, and educational inequality simultaneously. Critics, however, warned that such (ii)_______ risked diluting the initiative's impact, arguing that a more (iii)_______ approach targeting a single issue would yield more tangible results.",
    choices: [
      "i: sweeping",
      "i: modest",
      "i: partisan",
      "ii: overreach",
      "ii: parsimony",
      "ii: pragmatism",
      "iii: focused",
      "iii: ambitious",
      "iii: equivocal",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The legislation addresses three major issues simultaneously, making it broad in scope: blank (i) = 'sweeping' (wide in range or effect). Critics worry this breadth will weaken the impact, calling it 'overreach' (blank ii, going beyond what is appropriate or advisable). They prefer targeting one issue: blank (iii) = 'focused' (concentrated on a single area). 'Modest' (limited in scope) contradicts addressing three issues. 'Partisan' (biased toward one party) does not describe scope. 'Parsimony' (extreme frugality) does not describe ambition of scope. 'Pragmatism' (practical approach) would be positive, not a warning. 'Ambitious' is the opposite of the narrower approach critics want. 'Equivocal' (ambiguous) does not mean targeted.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-exp-022",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "medium",
    text: "Although the researcher's early publications were (i)_______, characterized by tentative hypotheses and modest claims, her later work became increasingly (ii)_______, advancing bold theories with a confidence that some colleagues regarded as (iii)_______ given the still-limited evidence.",
    choices: [
      "i: circumspect",
      "i: audacious",
      "i: prolix",
      "ii: assertive",
      "ii: reticent",
      "ii: methodical",
      "iii: premature",
      "iii: laudable",
      "iii: overdue",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The early work featured 'tentative hypotheses and modest claims,' indicating caution: blank (i) = 'circumspect' (wary, unwilling to take risks). 'Although' signals a shift: the later work advanced 'bold theories with confidence,' becoming blank (ii) = 'assertive' (confident and forceful). Colleagues viewed this confidence as inappropriate given limited evidence: blank (iii) = 'premature' (occurring before the proper time). 'Audacious' (bold) contradicts tentative and modest. 'Prolix' (using too many words) addresses style, not caution. 'Reticent' (reserved) does not describe bold confidence. 'Methodical' (systematic) addresses process, not assertiveness. 'Laudable' (praiseworthy) contradicts the colleagues' skepticism. 'Overdue' (delayed beyond expected time) would mean the confidence was welcome, not questioned.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-exp-023",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The historian's methodology was (i)_______ in that she refused to privilege any single type of source material; her synthesis of diplomatic correspondence, popular pamphlets, and private diaries produced an account that was remarkably (ii)_______, though some scholars found the resulting narrative so (iii)_______ that it resisted the kind of clear thesis statement academic convention demands.",
    choices: [
      "i: eclectic",
      "i: parochial",
      "i: antiquated",
      "ii: multifaceted",
      "ii: tendentious",
      "ii: homogeneous",
      "iii: protean",
      "iii: dogmatic",
      "iii: laconic",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The historian drew from multiple, diverse source types without privileging any: blank (i) = 'eclectic' (deriving ideas from a broad range of sources). The synthesis of varied sources produced a rich, many-sided account: blank (ii) = 'multifaceted' (having many aspects). However, this complexity made the narrative resistant to a single thesis — it was too changeable and varied: blank (iii) = 'protean' (tending to change frequently; versatile). 'Parochial' (having a narrow outlook) contradicts using diverse sources. 'Antiquated' (old-fashioned) does not describe methodological breadth. 'Tendentious' (biased) contradicts refusing to privilege any source. 'Homogeneous' (uniform) contradicts the diversity of the account. 'Dogmatic' (asserting opinions as undeniably true) contradicts resisting a clear thesis. 'Laconic' (using very few words) addresses brevity, not complexity.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-exp-024",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The philosopher contended that moral intuitions, far from being (i)_______ guides to ethical truth, are largely the product of evolutionary pressures that (ii)_______ survival rather than justice; consequently, she argued, any ethical theory that takes such intuitions as its foundation is built on ground that is fundamentally (iii)_______.",
    choices: [
      "i: reliable",
      "i: fallible",
      "i: superfluous",
      "ii: favored",
      "ii: impeded",
      "ii: transcended",
      "iii: unstable",
      "iii: hallowed",
      "iii: empirical",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The philosopher argues moral intuitions are not trustworthy. 'Far from being' signals the blank is what the philosopher denies: blank (i) = 'reliable' (consistently good in quality; dependable). The intuitions evolved to serve biological fitness, not moral correctness: evolutionary pressures 'favored' (blank ii) survival over justice. Therefore, ethical theories built on these intuitions rest on shaky foundations: blank (iii) = 'unstable' (prone to change; not firmly established). 'Fallible' (capable of error) would mean the philosopher agrees intuitions can err, which makes 'far from being fallible' wrong logically. 'Superfluous' (unnecessary) addresses relevance, not accuracy. 'Impeded' (obstructed) contradicts the idea that evolution shaped the intuitions. 'Transcended' (surpassed) does not logically fit with evolutionary pressures and survival. 'Hallowed' (honored, revered) would make the foundation seem positive. 'Empirical' (based on observation) addresses methodology, not soundness.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-exp-025",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The architect's design philosophy was (i)_______ in the extreme: she believed that every ornamental element was a (ii)_______ that distracted from a building's essential purpose. Her detractors, however, argued that such uncompromising minimalism produced structures that, however functionally efficient, were aesthetically (iii)_______.",
    choices: [
      "i: austere",
      "i: ostentatious",
      "i: eclectic",
      "ii: superfluity",
      "ii: necessity",
      "ii: complement",
      "iii: sterile",
      "iii: sumptuous",
      "iii: provocative",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The architect strips away all ornament, embodying extreme simplicity: blank (i) = 'austere' (severely simple; without excess). She views every ornamental element as an unnecessary addition: blank (ii) = 'superfluity' (the state of being superfluous; an unnecessary thing). Critics say the resulting buildings lack aesthetic appeal despite being functional: blank (iii) = 'sterile' (lacking in imagination, creativity, or excitement). 'Ostentatious' (showy) is the opposite of minimalism. 'Eclectic' (drawing from diverse sources) contradicts a single-minded minimalism. 'Necessity' (something essential) is the opposite of what she thinks ornament is. 'Complement' (something that completes) would mean ornament enhances rather than distracts. 'Sumptuous' (splendid, luxurious) contradicts the lack of aesthetic appeal. 'Provocative' (stimulating thought) does not capture the deadness critics perceive.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-exp-026",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The memoirist's candor about her own failings lends her writing a (i)_______ that readers find disarming; rather than (ii)_______ her mistakes behind a veil of self-justification, she examines them with an almost clinical detachment that paradoxically makes her more (iii)_______ to her audience, not less.",
    choices: [
      "i: vulnerability",
      "i: grandeur",
      "i: opacity",
      "ii: concealing",
      "ii: exaggerating",
      "ii: cataloguing",
      "iii: sympathetic",
      "iii: inscrutable",
      "iii: formidable",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The memoirist is candid about failings, which readers find 'disarming' — this openness creates a sense of exposed emotional honesty: blank (i) = 'vulnerability' (the quality of being open to emotional hurt). Instead of hiding mistakes behind self-justification, she examines them directly: blank (ii) = 'concealing' (hiding). This honesty paradoxically makes readers connect with her more: blank (iii) = 'sympathetic' (easy to feel warmth or understanding toward). 'Grandeur' (impressiveness) does not follow from candor about failings. 'Opacity' (obscurity) contradicts candor. 'Exaggerating' (overstating) does not fit with 'self-justification.' 'Cataloguing' (listing systematically) would not require a 'veil.' 'Inscrutable' (impossible to understand) contradicts the openness described. 'Formidable' (inspiring fear or respect through being impressively powerful) does not follow from clinical examination of one's own failures.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-exp-027",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The scientific community's initial (i)_______ toward the theory gradually gave way to grudging acceptance as successive experiments (ii)_______ its predictions with increasing precision; what had seemed like a(n) (iii)_______ conjecture proved, over two decades, to be one of the most robust models in the field.",
    choices: [
      "i: skepticism",
      "i: enthusiasm",
      "i: indifference",
      "ii: corroborated",
      "ii: undermined",
      "ii: reformulated",
      "iii: implausible",
      "iii: orthodox",
      "iii: self-evident",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The community moved from doubt to acceptance, so the initial reaction was doubt: blank (i) = 'skepticism' (a doubting attitude). Experiments confirmed the theory's predictions: blank (ii) = 'corroborated' (confirmed or gave support to). The theory initially seemed unlikely but proved durable: blank (iii) = 'implausible' (not seeming reasonable or probable). 'Enthusiasm' (eager enjoyment) contradicts the shift to 'grudging acceptance.' 'Indifference' (lack of interest) does not give way to grudging acceptance. 'Undermined' (weakened) contradicts growing acceptance. 'Reformulated' (expressed differently) does not describe experimental confirmation. 'Orthodox' (conforming to accepted views) contradicts the idea of a surprising theory. 'Self-evident' (obvious) would not require two decades of experimental validation.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-exp-028",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The anthropologist argued that the ritual, far from being a mere (i)_______ survival from an earlier era, served a vital contemporary function: by requiring participants to (ii)_______ their individual desires in favor of collective goals, it reinforced the social bonds that made the community's precarious existence in a harsh environment (iii)_______.",
    choices: [
      "i: vestigial",
      "i: innovative",
      "i: utilitarian",
      "ii: subordinate",
      "ii: articulate",
      "ii: indulge",
      "iii: viable",
      "iii: monotonous",
      "iii: conspicuous",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The anthropologist disputes the view that the ritual is a useless leftover from the past: blank (i) = 'vestigial' (remaining as a trace of something that once existed; no longer functional). Instead, the ritual requires participants to place collective goals above personal ones: blank (ii) = 'subordinate' (treat as of lesser importance). This strengthens social bonds, making survival in harsh conditions possible: blank (iii) = 'viable' (capable of working successfully; feasible). 'Innovative' (introducing new methods) does not describe a survival from an earlier era. 'Utilitarian' (designed to be useful) would support the ritual's value, not dismiss it. 'Articulate' (express coherently) does not fit with 'in favor of collective goals.' 'Indulge' (allow oneself to enjoy) is the opposite of sacrificing individual desires. 'Monotonous' (lacking variety; tedious) does not relate to the ability to survive. 'Conspicuous' (clearly visible) does not describe the enabling of community survival.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-exp-029",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The novelist's admirers praise her narrative voice as (i)_______, noting how she adopts the idioms and rhythms of each character she inhabits; her detractors, by contrast, see the same quality as evidence of a fundamental (ii)_______, arguing that beneath the virtuosic mimicry lies no (iii)_______ artistic vision that the author can call her own.",
    choices: [
      "i: chameleonic",
      "i: strident",
      "i: ponderous",
      "ii: hollowness",
      "ii: profundity",
      "ii: consistency",
      "iii: distinctive",
      "iii: derivative",
      "iii: collaborative",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The novelist adapts her voice to each character, changing like a chameleon: blank (i) = 'chameleonic' (readily changing or variable). Admirers see this as a strength, but detractors see it as revealing emptiness at the core — 'virtuosic mimicry' with nothing underneath: blank (ii) = 'hollowness' (the quality of being empty or lacking substance). The detractors claim there is no unique artistic identity: blank (iii) = 'distinctive' (characteristic and unique). 'Strident' (loud, harsh) does not describe adaptive narration. 'Ponderous' (slow, clumsy) does not describe versatile mimicry. 'Profundity' (great depth of insight) is a positive quality that detractors would not attribute. 'Consistency' (uniformity) is not inherently negative and does not capture the charge of emptiness. 'Derivative' (imitative of others' work) would mean the detractors acknowledge some vision, just a copied one. 'Collaborative' (involving joint effort) does not address artistic identity.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
  {
    id: "gre-tc-exp-030",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-triple"],
    difficulty: "hard",
    text: "The economist's analysis was (i)_______ in its logic yet (ii)_______ in its conclusions: starting from premises that no one could reasonably dispute, she arrived at policy recommendations so radical that even her ideological allies found them (iii)_______ to endorse publicly.",
    choices: [
      "i: impeccable",
      "i: specious",
      "i: rudimentary",
      "ii: incendiary",
      "ii: anodyne",
      "ii: tautological",
      "iii: impolitic",
      "iii: imperative",
      "iii: straightforward",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    correctAnswerC: 6,
    explanation:
      "The analysis starts from indisputable premises with flawless reasoning: blank (i) = 'impeccable' (in accordance with the highest standards; faultless). 'Yet' signals contrast: the conclusions are provocatively extreme — blank (ii) = 'incendiary' (tending to create public disturbances or violence; inflammatory). Even allies found the recommendations too politically dangerous to support openly: blank (iii) = 'impolitic' (failing to possess or display prudence; unwise). 'Specious' (superficially plausible but actually wrong) contradicts the undisputed premises. 'Rudimentary' (involving basic principles) does not capture logical rigor. 'Anodyne' (unlikely to provoke) is the opposite of radical. 'Tautological' (saying the same thing twice) does not describe radical conclusions. 'Imperative' (of vital importance) would mean allies felt compelled to endorse, not reluctant. 'Straightforward' (easy) does not capture the political danger.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-tc",
    threePartColumns: ["Blank (i)", "Blank (ii)", "Blank (iii)"],
  },
];
