import { Question } from "@/types";

export const greVerbalSEQuestions: Question[] = [
  // ─── EASY (6 questions) ─────────────────────────────────────────────
  {
    id: "gre-se-001",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The new employee's _______ attitude quickly won over her initially skeptical colleagues.",
    choices: ["affable", "caustic", "genial", "indifferent", "belligerent", "meticulous"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The employee 'won over' skeptical colleagues, meaning she charmed them. Both 'affable' (friendly, good-natured) and 'genial' (friendly, cheerful) describe pleasant attitudes that would win people over and produce equivalent sentences. 'Caustic' (harsh), 'indifferent' (uninterested), 'belligerent' (hostile) would not win over colleagues. 'Meticulous' (careful) doesn't match the winning-over context.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-002",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The politician's _______ speech, lasting nearly three hours, tested the patience of even his most loyal supporters.",
    choices: ["verbose", "eloquent", "loquacious", "succinct", "inflammatory", "poignant"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The speech lasted 'nearly three hours' and 'tested patience,' indicating it was excessively wordy. Both 'verbose' (using more words than necessary) and 'loquacious' (tending to talk at great length) produce equivalent sentences describing an overly long speech. 'Eloquent' (fluent, persuasive) and 'poignant' (emotionally moving) are positive traits that wouldn't test patience. 'Succinct' (concise) contradicts the three-hour length. 'Inflammatory' (provocative) doesn't address the length issue.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-003",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The detective found the witness's account _______, as it contradicted every piece of physical evidence collected at the scene.",
    choices: ["dubious", "compelling", "suspect", "cogent", "meticulous", "forthright"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "Because the account 'contradicted every piece of physical evidence,' the detective would find it untrustworthy. Both 'dubious' (doubtful, questionable) and 'suspect' (not to be relied upon) produce equivalent sentences conveying the detective's distrust. 'Compelling' (convincing) and 'cogent' (clear and logical) are near-synonyms of each other but contradict the sentence's logic. 'Meticulous' (thorough) and 'forthright' (direct and honest) don't fit the context of distrusting testimony.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-004",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "Despite the book's _______ plot, the author's vivid prose style kept readers engaged from beginning to end.",
    choices: ["riveting", "predictable", "trite", "original", "convoluted", "suspenseful"],
    correctAnswer: 1,
    correctAnswerB: 2,
    explanation:
      "The word 'despite' signals a contrast: the plot had a negative quality, yet readers stayed engaged because of the prose. Both 'predictable' (easily foreseen) and 'trite' (lacking originality, overused) describe a plot that is unimpressive yet could be overcome by strong writing. 'Riveting' (fascinating), 'original' (novel), and 'suspenseful' (creating tension) are all positive plot qualities that wouldn't require 'despite.' 'Convoluted' (complex) could be negative, but it has no matching synonym among the choices.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-005",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The professor's explanation was so _______ that even students with no background in physics could follow the argument.",
    choices: ["opaque", "lucid", "pellucid", "abstruse", "pedantic", "provisional"],
    correctAnswer: 1,
    correctAnswerB: 2,
    explanation:
      "Students with no background could follow the argument, meaning the explanation was extremely clear. Both 'lucid' (easy to understand) and 'pellucid' (transparently clear) produce equivalent sentences describing an accessible explanation. 'Opaque' (hard to understand) and 'abstruse' (difficult to comprehend) are the opposite of what's needed. 'Pedantic' (excessively concerned with minor details) and 'provisional' (temporary) don't describe clarity.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-006",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "easy",
    text: "The comedian's _______ remarks about the celebrity's personal life drew gasps from the audience and condemnation from critics.",
    choices: ["tactful", "acerbic", "bland", "caustic", "generous", "whimsical"],
    correctAnswer: 1,
    correctAnswerB: 3,
    explanation:
      "The remarks drew 'gasps' and 'condemnation,' indicating they were sharp and cutting. Both 'acerbic' (sharp, forthright, and harsh) and 'caustic' (biting, sarcastic) produce equivalent sentences describing cruelly pointed humor. 'Tactful' (showing sensitivity) and 'generous' (kind) are the opposite of what provoked condemnation. 'Bland' (lacking strong qualities) wouldn't draw gasps. 'Whimsical' (playfully quaint) doesn't carry the necessary harshness.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },

  // ─── MEDIUM (8 questions) ──────────────────────────────────────────
  {
    id: "gre-se-007",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "Far from being the _______ figure his opponents portrayed, the senator was in fact deeply principled and unwilling to compromise on matters of ethics.",
    choices: ["venal", "steadfast", "mercenary", "resolute", "ingenuous", "doctrinaire"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The sentence contrasts what opponents claimed ('far from being') with the senator's true principled nature. Opponents must have portrayed him as corrupt or motivated by money. Both 'venal' (susceptible to bribery) and 'mercenary' (motivated primarily by financial gain) produce equivalent sentences describing the false accusation of corruption. 'Steadfast' and 'resolute' are synonyms meaning firm and unwavering, but they describe positive traits consistent with his actual character, not the opponents' portrayal. 'Ingenuous' (innocent, unsophisticated) and 'doctrinaire' (rigidly devoted to theory) don't fit the corruption contrast.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-008",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The scholar's argument, though presented with great confidence, was ultimately _______, resting on assumptions that had been disproved decades earlier.",
    choices: ["cogent", "specious", "fallacious", "novel", "prescient", "trenchant"],
    correctAnswer: 1,
    correctAnswerB: 2,
    explanation:
      "The argument rests on 'disproved assumptions,' meaning it appears convincing but is actually flawed. Both 'specious' (superficially plausible but actually wrong) and 'fallacious' (based on a mistaken belief, logically unsound) produce equivalent sentences describing a deceptively flawed argument. 'Cogent' (clear and convincing) and 'trenchant' (incisive, effective) describe strong arguments. 'Novel' (new and original) and 'prescient' (having foresight) don't address logical validity.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-009",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The CEO's _______ management style, in which she sought input from employees at every level before making decisions, fostered a culture of mutual respect.",
    choices: ["autocratic", "collaborative", "capricious", "participatory", "imperious", "mercurial"],
    correctAnswer: 1,
    correctAnswerB: 3,
    explanation:
      "The CEO 'sought input from employees at every level,' indicating an inclusive approach. Both 'collaborative' (involving joint effort) and 'participatory' (involving participation from all) produce equivalent sentences describing a management style that includes others. 'Autocratic' (ruling with absolute power) and 'imperious' (domineering) are synonyms describing the opposite approach. 'Capricious' (unpredictable) and 'mercurial' (changeable) are tempting synonyms but don't match the context of seeking input.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-010",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "Critics praised the documentary for its _______ examination of the crisis, noting that it presented multiple perspectives without advocating for any single position.",
    choices: ["partisan", "dispassionate", "cursory", "impartial", "tendentious", "superficial"],
    correctAnswer: 1,
    correctAnswerB: 3,
    explanation:
      "The documentary 'presented multiple perspectives without advocating' for one, indicating objectivity. Both 'dispassionate' (not influenced by strong emotion; rational) and 'impartial' (treating all sides equally) produce equivalent sentences describing fair, balanced coverage. 'Partisan' (prejudiced in favor of a cause) and 'tendentious' (expressing a strong opinion) are the opposite. 'Cursory' (hasty, not thorough) and 'superficial' (lacking depth) are a tempting pair but contradict the idea of an examination praised by critics.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-011",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The region's inhabitants, long accustomed to hardship, displayed a _______ resilience that impressed the aid workers who arrived after the earthquake.",
    choices: ["fleeting", "stolid", "stoic", "flamboyant", "histrionic", "ephemeral"],
    correctAnswer: 1,
    correctAnswerB: 2,
    explanation:
      "People 'long accustomed to hardship' who impressed aid workers with their resilience were enduring suffering without complaint. Both 'stolid' (calm, dependable, showing little emotion) and 'stoic' (enduring pain without showing feelings) produce equivalent sentences describing quiet, unflinching endurance. 'Fleeting' and 'ephemeral' are synonyms meaning short-lived, but they contradict 'long accustomed' resilience. 'Flamboyant' (showy) and 'histrionic' (overly dramatic) contradict the quiet nature of the resilience described.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-012",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The author's tone throughout the memoir is notably _______, reflecting on past mistakes with gentle humor rather than bitterness.",
    choices: ["sardonic", "self-deprecating", "vitriolic", "rueful", "sanctimonious", "acrimonious"],
    correctAnswer: 1,
    correctAnswerB: 3,
    explanation:
      "The author reflects on 'past mistakes with gentle humor rather than bitterness,' suggesting a mild, regretful but good-natured tone. Both 'self-deprecating' (modest about oneself, understating one's abilities with humor) and 'rueful' (expressing sorrow or regret in a wry, humorous way) produce equivalent sentences. 'Sardonic' (grimly mocking) is too harsh for 'gentle humor.' 'Vitriolic' (filled with bitter criticism) and 'acrimonious' (angry, bitter) directly contradict 'rather than bitterness.' 'Sanctimonious' (making a show of moral superiority) doesn't match regretful self-reflection.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-013",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "Although the mayor projected an image of _______, several former aides reported that behind closed doors he was prone to fits of rage and vindictiveness.",
    choices: ["equanimity", "composure", "belligerence", "volatility", "avarice", "austerity"],
    correctAnswer: 0,
    correctAnswerB: 1,
    explanation:
      "The contrast word 'although' sets up a discrepancy between the mayor's public image and his private behavior of 'rage and vindictiveness.' His projected image must be the opposite: calm and even-tempered. Both 'equanimity' (mental calmness and composure) and 'composure' (the state of being calm and self-controlled) produce equivalent sentences. 'Belligerence' (aggressive hostility) and 'volatility' (tendency to change rapidly and unpredictably) would align with the private behavior, not contrast with it. 'Avarice' (extreme greed) and 'austerity' (sternness, strict self-discipline) don't relate to the calm-versus-rage contrast.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-014",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "medium",
    text: "The negotiations, which had seemed close to a resolution, were suddenly _______ by the introduction of a previously undisclosed demand.",
    choices: ["facilitated", "stymied", "expedited", "thwarted", "ratified", "bolstered"],
    correctAnswer: 1,
    correctAnswerB: 3,
    explanation:
      "A 'previously undisclosed demand' disrupted negotiations that had 'seemed close to resolution,' indicating an obstruction. Both 'stymied' (prevented from making progress) and 'thwarted' (prevented from accomplishing a purpose) produce equivalent sentences describing how the new demand blocked progress. 'Facilitated' (made easier) and 'expedited' (made to happen sooner) suggest acceleration, not obstruction. 'Ratified' (formally approved) implies completion. 'Bolstered' (supported, strengthened) contradicts the idea of disruption.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },

  // ─── HARD (6 questions) ─────────────────────────────────────────────
  {
    id: "gre-se-015",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The billionaire's _______ lifestyle, marked by reused tea bags and secondhand furniture, stood in stark contrast to the lavish spending of her peers.",
    choices: ["parsimonious", "ostentatious", "munificent", "penurious", "profligate", "ascetic"],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The billionaire reuses tea bags and buys secondhand furniture despite being wealthy, indicating extreme frugality. Both 'parsimonious' (excessively unwilling to spend money) and 'penurious' (extremely stingy) produce equivalent sentences describing miserly behavior. 'Ascetic' (characterized by self-denial) is tempting but describes self-discipline for spiritual purposes, not mere stinginess, and lacks a synonym pair in the list. 'Ostentatious' (showy), 'munificent' (very generous), and 'profligate' (recklessly wasteful) all describe the opposite of frugality.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-016",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The young diplomat's _______ demeanor at the high-stakes summit surprised seasoned negotiators, who had expected someone of her limited experience to be more assertive.",
    choices: ["diffident", "imperious", "timorous", "audacious", "ebullient", "punctilious"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "The negotiators expected assertiveness but found the opposite, suggesting the diplomat was shy and hesitant. Both 'diffident' (modest, lacking self-confidence) and 'timorous' (showing nervousness or a lack of courage) produce equivalent sentences describing a reserved, unassertive demeanor. 'Imperious' (domineering) and 'audacious' (showing bold willingness to take risks) describe assertive behavior, the opposite of what's needed. 'Ebullient' (enthusiastic) doesn't address assertiveness. 'Punctilious' (showing great attention to detail) relates to meticulousness, not timidity.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-017",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The professor's lectures on quantum mechanics were so _______ that only a handful of graduate students could follow her reasoning, while the rest sat in bewildered silence.",
    choices: ["recondite", "pellucid", "abstruse", "didactic", "prosaic", "accessible"],
    correctAnswer: 0,
    correctAnswerB: 2,
    explanation:
      "Only a 'handful of graduate students' could follow the lectures, and the rest sat in 'bewildered silence,' meaning the content was extremely difficult to understand. Both 'recondite' (little known, obscure, dealing with abstruse subject matter) and 'abstruse' (difficult to understand) produce equivalent sentences describing impenetrably complex lectures. 'Pellucid' (easily understood) and 'accessible' (easy to understand) are the opposite. 'Didactic' (intended to teach) and 'prosaic' (lacking imagination, dull) don't describe difficulty of comprehension.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-018",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The critic dismissed the novel as _______, arguing that its supposedly revolutionary narrative techniques had been employed by dozens of writers in the preceding decade.",
    choices: ["derivative", "groundbreaking", "seminal", "epigonic", "provocative", "prescient"],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation:
      "The critic argues the techniques had already been used by 'dozens of writers,' meaning the novel merely imitated earlier work. Both 'derivative' (imitative of the work of another artist) and 'epigonic' (of or relating to an inferior imitator of a distinguished original) produce equivalent sentences describing unoriginal work. 'Groundbreaking' (innovative) and 'seminal' (strongly influencing later developments) are synonyms suggesting originality, the opposite of the critic's view. 'Provocative' (stimulating thought) and 'prescient' (having foresight) don't address the question of originality versus imitation.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-019",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "What makes the historian's account so valuable is its _______ treatment of a period usually discussed in overly simplistic terms; she reveals the era's contradictions without attempting to resolve them into a neat narrative.",
    choices: ["reductive", "nuanced", "tendentious", "textured", "polemical", "hagiographic"],
    correctAnswer: 1,
    correctAnswerB: 3,
    explanation:
      "The historian reveals 'contradictions without attempting to resolve them,' contrasting with 'overly simplistic terms.' This indicates a sophisticated, multifaceted treatment. Both 'nuanced' (characterized by subtle distinctions) and 'textured' (having rich complexity and depth) produce equivalent sentences describing a detailed, layered analysis. 'Reductive' (tending to present in simplified terms) is the opposite of what's described. 'Tendentious' (expressing a strong opinion) and 'polemical' (involving strongly critical attack) suggest bias, which contradicts the balanced treatment. 'Hagiographic' (treating the subject with undue reverence) implies a one-sided, worshipful account.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
  {
    id: "gre-se-020",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence", "vocabulary-in-context"],
    difficulty: "hard",
    text: "The ambassador's reputation for _______ made her the ideal choice for the sensitive mission; where others might have inadvertently given offense, she navigated cultural differences with effortless grace.",
    choices: ["gaucherie", "perspicacity", "diplomacy", "brusqueness", "tactfulness", "erudition"],
    correctAnswer: 2,
    correctAnswerB: 4,
    explanation:
      "The ambassador 'navigated cultural differences with effortless grace' where others might have 'given offense,' indicating exceptional social sensitivity. Both 'diplomacy' (skill in handling sensitive matters) and 'tactfulness' (showing sensitivity in dealing with others) produce equivalent sentences describing her ability to handle delicate situations adroitly. 'Gaucherie' (unsophisticated, socially awkward behavior) and 'brusqueness' (abrupt, blunt manner) describe the opposite quality. 'Perspicacity' (keen mental perception) is tempting because it's a positive trait, but it describes intellectual sharpness, not social grace. 'Erudition' (great learning) similarly describes knowledge, not interpersonal skill.",
    source: { name: "GRE Practice — Original", type: "original" as const },
    chapterId: "gre-verbal-se",
  },
];
