import { Question } from "@/types";

export const greVerbalQuestions: Question[] = [
  {
    id: "gre-v-001",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-single"],
    difficulty: "medium",
    text: "The researcher's findings were so _______ that even her harshest critics were forced to acknowledge the validity of her conclusions.",
    choices: ["compelling", "ambiguous", "derivative", "inconsequential", "speculative"],
    correctAnswer: 0,
    explanation: "The sentence indicates that the findings convinced even critics, which means they must have been 'compelling' — powerfully persuasive. 'Ambiguous' (unclear), 'derivative' (unoriginal), 'inconsequential' (unimportant), and 'speculative' (based on guessing) all contradict the idea of convincing skeptics.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-v-002",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["sentence-equivalence"],
    difficulty: "medium",
    text: "The novel's protagonist is _______ figure, simultaneously admired for her courage and reviled for her ruthlessness.",
    choices: ["a polarizing", "an insignificant", "a predictable", "a controversial", "a mundane"],
    correctAnswer: 0,
    explanation: "The sentence describes someone who is both 'admired' and 'reviled,' indicating divided opinions. Both 'polarizing' and 'controversial' (answer D) capture this idea of provoking strong, opposing reactions. These two words produce sentences that are closest in meaning.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-v-003",
    section: "verbal",
    type: "reading-comprehension",
    themes: ["rc-main-idea"],
    difficulty: "medium",
    passage: "The discovery of deep-sea hydrothermal vents in 1977 fundamentally altered scientists' understanding of the conditions necessary for life. Prior to this discovery, it was widely assumed that all life on Earth ultimately depended on photosynthesis — the conversion of sunlight into energy by plants and certain microorganisms. The vent ecosystems, however, thrived in complete darkness at crushing pressures, sustained instead by chemosynthesis, a process in which bacteria derive energy from chemicals such as hydrogen sulfide expelled from the vents. This finding not only expanded the known boundaries of life on Earth but also invigorated the search for extraterrestrial life, particularly on moons like Europa, where subsurface oceans might harbor similar chemical energy sources.",
    text: "Which of the following best describes the main idea of the passage?",
    choices: [
      "The discovery of hydrothermal vents challenged assumptions about life's requirements and broadened the search for life beyond Earth.",
      "Chemosynthesis is a more efficient energy source than photosynthesis for sustaining complex ecosystems.",
      "Europa is the most likely location for discovering extraterrestrial life in our solar system.",
      "Deep-sea organisms have evolved unique adaptations that make them fundamentally different from surface-dwelling species.",
      "The 1977 expedition was primarily motivated by the desire to find evidence of extraterrestrial life.",
    ],
    correctAnswer: 0,
    explanation: "The passage describes how the discovery of hydrothermal vents changed the understanding of life's requirements (from photosynthesis-dependent to chemosynthesis-capable) and how this expanded the search for extraterrestrial life. Answer A captures both key ideas. The other options either overstate claims (B, C), introduce unsupported ideas (D), or misstate motivation (E).",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-v-004",
    section: "verbal",
    type: "text-completion",
    themes: ["text-completion-double"],
    difficulty: "hard",
    text: "While the professor's lectures were often (i)_______, his published papers were models of (ii)_______, presenting complex arguments with remarkable economy of expression.",
    choices: [
      "i: prolix",
      "i: terse",
      "i: lucid",
      "ii: concision",
      "ii: verbosity",
      "ii: obscurity",
    ],
    correctAnswer: 0,
    correctAnswerB: 3,
    explanation: "'While' signals a contrast between lectures and papers. The papers are described as having 'remarkable economy of expression,' meaning they are concise. So blank (ii) = 'concision.' The contrasting lectures must be the opposite: 'prolix' (wordy/long-winded). 'Terse' would mean brief (no contrast), and 'lucid' means clear (doesn't contrast with concision).",
    source: { name: "Original", type: "original" },
    twoPartColumns: ["Blank (i)", "Blank (ii)"],
  },
  {
    id: "gre-v-005",
    section: "verbal",
    type: "reading-comprehension",
    themes: ["rc-inference"],
    difficulty: "easy",
    passage: "The concept of 'emotional intelligence' — the ability to recognize, understand, and manage one's own emotions and those of others — has gained significant traction in both academic psychology and corporate training programs. Proponents argue that emotional intelligence is a better predictor of professional success than traditional IQ measures, citing studies showing that managers with high emotional intelligence foster more productive teams. Critics, however, contend that the concept is too broadly defined to be scientifically useful and that many of the studies supporting it suffer from methodological limitations.",
    text: "It can be inferred from the passage that critics of emotional intelligence would most likely agree with which of the following?",
    choices: [
      "Emotional intelligence has no relevance to workplace performance.",
      "The scientific rigor of emotional intelligence research needs improvement.",
      "Traditional IQ measures are the sole predictor of professional success.",
      "Corporate training programs should avoid all references to emotions.",
      "Emotional intelligence cannot be measured under any circumstances.",
    ],
    correctAnswer: 1,
    explanation: "The passage states that critics believe 'many of the studies supporting it suffer from methodological limitations.' This directly implies they think the research needs more scientific rigor. The critics don't say EI is irrelevant (A), that IQ is the sole predictor (C), that programs should avoid emotions (D), or that EI can never be measured (E) — they argue the concept is too broad and studies are flawed.",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-v-006",
    section: "verbal",
    type: "text-completion",
    themes: ["vocabulary-in-context"],
    difficulty: "easy",
    text: "Although the artist's early works were _______, her later paintings demonstrated a striking mastery of color and composition.",
    choices: ["accomplished", "mediocre", "innovative", "celebrated", "provocative"],
    correctAnswer: 1,
    explanation: "'Although' signals a contrast between early and later works. The later works showed 'mastery,' so the early works must have been less skilled. 'Mediocre' (of only moderate quality) provides this contrast. The other options all suggest positive qualities that wouldn't contrast with 'mastery.'",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-v-007",
    section: "verbal",
    type: "reading-comprehension",
    themes: ["rc-structure"],
    difficulty: "hard",
    passage: "In recent decades, behavioral economists have challenged the rational-actor model that long dominated economic theory. Classical economics assumed that individuals consistently make decisions that maximize their utility — that is, they weigh costs and benefits accurately and choose optimally. Behavioral economists, drawing on psychological research, have demonstrated numerous systematic biases that lead people to make irrational choices. Loss aversion, for instance, causes people to weigh potential losses more heavily than equivalent gains, leading to risk-averse behavior even when the expected value favors risk-taking. Similarly, the anchoring effect shows that people's judgments are disproportionately influenced by the first piece of information they encounter, regardless of its relevance.\n\nYet some defenders of classical economics argue that these findings, while interesting at the individual level, do not undermine the rational-actor model's usefulness for predicting aggregate market behavior. Markets, they contend, are self-correcting: even if individual actors make irrational decisions, competitive pressures and arbitrage opportunities ensure that market outcomes approximate what rational-actor models predict.",
    text: "The passage is primarily organized by",
    choices: [
      "presenting a challenge to an established theory and then describing a defense of that theory",
      "comparing two equivalent approaches to economic modeling",
      "chronologically tracing the development of behavioral economics",
      "arguing that classical economics should be entirely replaced by behavioral economics",
      "providing experimental evidence to refute classical economic theory",
    ],
    correctAnswer: 0,
    explanation: "Paragraph 1 presents behavioral economics as a challenge to the rational-actor model (the established theory). Paragraph 2 then describes how defenders of classical economics argue these findings don't undermine the model at the aggregate level. This is a classic 'challenge + defense' structure. The passage doesn't treat them as equivalent (B), isn't purely chronological (C), doesn't argue for replacement (D), or focus solely on experimental evidence (E).",
    source: { name: "Original", type: "original" },
  },
  {
    id: "gre-v-008",
    section: "verbal",
    type: "sentence-equivalence",
    themes: ["vocabulary-in-context"],
    difficulty: "easy",
    text: "The new employee's _______ attitude quickly won over her initially skeptical colleagues.",
    choices: ["affable", "caustic", "genial", "indifferent", "belligerent"],
    correctAnswer: 0,
    explanation: "The employee 'won over' skeptical colleagues, meaning she charmed them. Both 'affable' (friendly, good-natured) and 'genial' (friendly, cheerful) describe pleasant attitudes that would win people over. 'Caustic' (harsh), 'indifferent' (uninterested), and 'belligerent' (hostile) would not win over colleagues.",
    source: { name: "Original", type: "original" },
  },
];
