import { Chapter } from "@/types";

export const greQuantChapters: Chapter[] = [
  {
    id: "gre-quant-arithmetic",
    section: "quant",
    title: "Arithmetic Fundamentals",
    description: "Review integers, number properties, fractions, decimals, percents, ratios, and exponents for the GRE.",
    order: 1,
    topics: ["integers", "fractions-decimals-percents", "ratio-proportion", "exponents-roots"],
    frequency: "high",
    frequencyPercent: 25,
    estimatedMinutes: 35,
    practiceQuestionIds: ["gre-q-001", "gre-q-006", "gre-q-009"],
  },
  {
    id: "gre-quant-algebra",
    section: "quant",
    title: "Algebra",
    description: "Cover linear and quadratic equations, inequalities, functions, and algebraic word problems.",
    order: 2,
    topics: ["linear-equations", "quadratic-equations", "functions-graphs", "word-problems"],
    frequency: "high",
    frequencyPercent: 25,
    estimatedMinutes: 35,
    practiceQuestionIds: ["gre-q-002"],
  },
  {
    id: "gre-quant-geometry",
    section: "quant",
    title: "Geometry",
    description: "Study lines, angles, triangles, circles, polygons, coordinate geometry, and 3D figures.",
    order: 3,
    topics: ["lines-angles", "triangles", "circles", "quadrilaterals-polygons", "coordinate-geometry", "3d-geometry"],
    frequency: "medium",
    frequencyPercent: 20,
    estimatedMinutes: 35,
    practiceQuestionIds: ["gre-q-003", "gre-q-007"],
  },
  {
    id: "gre-quant-data-analysis",
    section: "quant",
    title: "Data Analysis",
    description: "Learn statistics, probability, counting methods, data interpretation, and normal distributions.",
    order: 4,
    topics: ["statistics-descriptive", "probability", "counting-combinatorics", "data-interpretation", "normal-distribution"],
    frequency: "high",
    frequencyPercent: 30,
    estimatedMinutes: 35,
    practiceQuestionIds: ["gre-q-004", "gre-q-005", "gre-q-008", "gre-q-010"],
  },
];
