import { Chapter } from "@/types";

export const greVerbalChapters: Chapter[] = [
  {
    id: "gre-verbal-tc",
    section: "verbal",
    title: "Text Completion Strategies",
    description: "Learn techniques for solving single-, double-, and triple-blank text completion questions on the GRE. Master signal words, sentence logic, and vocabulary-in-context.",
    order: 1,
    topics: ["text-completion-single", "text-completion-double", "text-completion-triple", "vocabulary-in-context"],
    frequency: "high",
    frequencyPercent: 28,
    estimatedMinutes: 35,
    practiceQuestionIds: [
      "gre-tc-001", "gre-tc-002", "gre-tc-003", "gre-tc-004", "gre-tc-005",
      "gre-tc-006", "gre-tc-007", "gre-tc-008", "gre-tc-009", "gre-tc-010",
      "gre-tc-011", "gre-tc-012", "gre-tc-013", "gre-tc-014", "gre-tc-015",
      "gre-tc-016", "gre-tc-017", "gre-tc-018", "gre-tc-019", "gre-tc-020",
      "gre-tc-021", "gre-tc-022", "gre-tc-023", "gre-tc-024", "gre-tc-025",
      "gre-tc-026", "gre-tc-027", "gre-tc-028", "gre-tc-029", "gre-tc-030",
    ],
  },
  {
    id: "gre-verbal-se",
    section: "verbal",
    title: "Sentence Equivalence",
    description: "Master the strategy of finding two answer choices that produce sentences with equivalent meaning. Build GRE-level vocabulary with synonym pairs.",
    order: 2,
    topics: ["sentence-equivalence", "vocabulary-in-context"],
    frequency: "high",
    frequencyPercent: 22,
    estimatedMinutes: 30,
    practiceQuestionIds: [
      "gre-se-001", "gre-se-002", "gre-se-003", "gre-se-004", "gre-se-005",
      "gre-se-006", "gre-se-007", "gre-se-008", "gre-se-009", "gre-se-010",
      "gre-se-011", "gre-se-012", "gre-se-013", "gre-se-014", "gre-se-015",
      "gre-se-016", "gre-se-017", "gre-se-018", "gre-se-019", "gre-se-020",
    ],
  },
  {
    id: "gre-verbal-rc",
    section: "verbal",
    title: "Reading Comprehension",
    description: "Develop strategies for main idea, detail, inference, structure, and critical reasoning questions on GRE passages across sciences, social sciences, and humanities.",
    order: 3,
    topics: ["rc-main-idea", "rc-detail", "rc-inference", "rc-structure", "rc-strengthen-weaken", "rc-vocab-in-passage", "rc-select-sentence"],
    frequency: "high",
    frequencyPercent: 50,
    estimatedMinutes: 45,
    practiceQuestionIds: [
      "gre-rc-001", "gre-rc-002", "gre-rc-003", "gre-rc-004", "gre-rc-005",
      "gre-rc-006", "gre-rc-007", "gre-rc-008", "gre-rc-009", "gre-rc-010",
      "gre-rc-011", "gre-rc-012", "gre-rc-013", "gre-rc-014", "gre-rc-015",
      "gre-rc-016", "gre-rc-017", "gre-rc-018", "gre-rc-019", "gre-rc-020",
      "gre-rc-021", "gre-rc-022", "gre-rc-023", "gre-rc-024", "gre-rc-025",
      "gre-rc-026", "gre-rc-027", "gre-rc-028", "gre-rc-029", "gre-rc-030",
    ],
  },
];
